/* FRONTLINE ZERO — playable release 3. All assets generated at runtime. */
(()=>{'use strict';
const $=s=>document.querySelector(s), clamp=(v,a,b)=>Math.max(a,Math.min(b,v)), lerp=(a,b,t)=>a+(b-a)*t;
const V=THREE.Vector3, UP=new V(0,1,0), STEP=1/60, HALF=44;
const defaults={version:1,xp:0,stats:{kills:0,deaths:0,matches:0,wins:0,shots:0,hits:0},mastery:{},history:[],loadout:{primary:0,secondary:6,attachment:'Red dot',uniform:'Olive'},settings:{sensitivity:1,adsSensitivity:.55,volume:.5,quality:'Automatic',scale:.85,fov:80,autoHop:false,autoSprint:false,assist:true,shake:true,invert:false,fps:true,bloom:true,inputMode:'Auto'},layout:{},config:{mode:'Team Deathmatch',map:'Iron Port',seed:2026,bots:8,difficulty:'Regular',limit:20,duration:180,weather:'Clear',time:'Sunset'}};
let save;try{save=JSON.parse(localStorage.getItem('fz-save-v1'));}catch(e){}if(!save||save.version!==1)save=structuredClone(defaults);for(const k of ['settings','stats','loadout','config'])save[k]=Object.assign({},defaults[k],save[k]);save.layout=save.layout||{};save.mastery=save.mastery||{};save.history=Array.isArray(save.history)?save.history.slice(-20):[];
function validateSave(){save.xp=Math.max(0,Number(save.xp)||0);save.loadout.primary=clamp(Number(save.loadout.primary)||0,0,7)|0;save.loadout.secondary=clamp(Number(save.loadout.secondary)||6,6,7)|0;for(const k of ['sensitivity','adsSensitivity','volume','scale','fov'])save.settings[k]=Number.isFinite(Number(save.settings[k]))?Number(save.settings[k]):defaults.settings[k];save.settings.sensitivity=clamp(save.settings.sensitivity,.2,3);save.settings.adsSensitivity=clamp(save.settings.adsSensitivity,.1,1.5);save.settings.volume=clamp(save.settings.volume,0,1);save.settings.scale=clamp(save.settings.scale,.4,1);save.settings.fov=clamp(save.settings.fov,65,105);if(!['Iron Port','Dust Valley','Greenfall','Neon District','Frostline'].includes(save.config.map))save.config.map='Iron Port';if(!['Team Deathmatch','Free-for-All','Gun Game','Sniper Only','Survival','Training Range','Custom Match'].includes(save.config.mode))save.config.mode='Team Deathmatch';save.config.seed=Number(save.config.seed)||2026;save.config.bots=clamp(Number(save.config.bots)||8,2,12);save.config.limit=clamp(Number(save.config.limit)||20,5,100);save.config.duration=clamp(Number(save.config.duration)||180,30,900);if(!['Recruit','Regular','Veteran','Elite'].includes(save.config.difficulty))save.config.difficulty='Regular';if(!['Auto','Keyboard / mouse','Touch'].includes(save.settings.inputMode))save.settings.inputMode='Auto';if(typeof save.layout!=='object'||Array.isArray(save.layout))save.layout={};for(const k of Object.keys(save.layout)){const a=save.layout[k];if(!a||!Number.isFinite(a.x)||!Number.isFinite(a.y))delete save.layout[k];else{a.x=clamp(a.x,3,97);a.y=clamp(a.y,5,95);a.size=clamp(Number(a.size)||60,35,160);a.opacity=clamp(Number(a.opacity)||.65,.2,1);}}}validateSave();
let saveTimer;function persist(){clearTimeout(saveTimer);saveTimer=setTimeout(()=>{try{localStorage.setItem('fz-save-v1',JSON.stringify(save));}catch(e){toast('Storage unavailable — this session is still playable.');}},250);}
function rng(seed){let a=seed|0;return()=>{a|=0;a=a+0x6D2B79F5|0;let t=Math.imul(a^a>>>15,1|a);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296;};}
const WEAPONS=[
{name:'C4 CARBINE',type:'rifle',damage:27,rate:.105,mag:30,reload:1.8,spread:.011,recoil:.012,range:90,color:0x555951},
{name:'AK-47',type:'rifle',damage:36,rate:.14,mag:30,reload:2.2,spread:.016,recoil:.022,range:85,color:0x7f5940},
{name:'VECTOR 9',type:'smg',damage:19,rate:.065,mag:32,reload:1.5,spread:.023,recoil:.009,range:38,color:0x434a48},
{name:'LONGSHOT .308',type:'sniper',damage:92,rate:1.05,mag:5,reload:2.7,spread:.002,recoil:.045,range:170,color:0x555c4c},
{name:'BREACH 12',type:'shotgun',damage:17,rate:.75,mag:8,reload:2.4,spread:.065,recoil:.038,range:24,pellets:8,color:0x4c4a44},
{name:'M240 SUPPORT',type:'lmg',damage:30,rate:.115,mag:70,reload:3.8,spread:.023,recoil:.019,range:100,color:0x424946},
{name:'P9 SERVICE',type:'pistol',damage:31,rate:.25,mag:15,reload:1.3,spread:.015,recoil:.021,range:45,color:0x3e4345},
{name:'R8 REVOLVER',type:'pistol',damage:62,rate:.5,mag:6,reload:2,spread:.01,recoil:.035,range:65,color:0x737d80}];
const MODES=['Team Deathmatch','Free-for-All','Gun Game','Sniper Only','Survival','Training Range','Custom Match'];
const MAPS=['Iron Port','Dust Valley','Greenfall','Neon District','Frostline'];
const THEMES=[{ground:0x817c68,sky:0xc1c9c9,fog:0xb1bbb7,accent:0xc0824b},{ground:0xbea274,sky:0xcbd2ca,fog:0xc9bfa5,accent:0x958976},{ground:0x58674c,sky:0xaebfbe,fog:0xa2b4a5,accent:0x687363},{ground:0x606969,sky:0x9eacb4,fog:0x929fa6,accent:0x8b8173},{ground:0xc4d4d6,sky:0xb3c9dc,fog:0xb6cbd3,accent:0x658495}];
const input={x:0,z:0,fire:false,ads:false,jump:false,crouch:false,sprint:false,lean:0};const keys={};
let appState='menu',editing=false,match=null,world=null,bots=[],yaw=0,pitch=0,clock=0,lastTime=0,accumulator=0,renderScale=save.settings.scale,fps=60,frameAvg=16,qualityCooldown=0,scope=0,weaponKick=0,flash=0,hitTime=0,hurtTime=0,shake=0,deathTimer=0;
const player={pos:new V(0,0,32),prev:new V(),vel:new V(),health:100,armor:50,grounded:true,coyote:0,jumpBuffer:0,slide:0,eye:1.65,team:0,alive:true,kills:0,deaths:0,headshots:0,damage:0,shots:0,hits:0,longest:0,tier:0,ammo:[30,15],slot:0,reload:0,fireCooldown:0,grenades:3,throwType:'Frag',invulnerable:0};
let renderer,scene,camera,sun,hemi,bloom,weaponRoot,gun,worldRoot,preview,previewYaw=Math.PI+.35;
const materials=new Map(),boxGeo=new THREE.BoxGeometry(1,1,1),sphereGeo=new THREE.SphereGeometry(1,8,6),cylinderGeo=new THREE.CylinderGeometry(1,1,1,8),tmpMatrix=new THREE.Matrix4(),tmpQuat=new THREE.Quaternion(),tmpPos=new V(),tmpScale=new V();
// Cached procedural PBR detail: no downloaded textures, and no per-frame texture work.
const surfaceTextures=new Map();
function surfaceTexture(kind){if(surfaceTextures.has(kind))return surfaceTextures.get(kind);const size=128,canvas=document.createElement('canvas');canvas.width=canvas.height=size;const ctx=canvas.getContext('2d'),random=rng(kind==='steel'?117:kind==='fabric'?229:kind==='soil'?337:449);ctx.fillStyle='#b9b9b9';ctx.fillRect(0,0,size,size);
for(let i=0;i<2200;i++){const shade=Math.floor(100+random()*110);ctx.fillStyle=`rgba(${shade},${shade},${shade},${kind==='fabric'?.18:.25})`;const x=random()*size,y=random()*size;ctx.fillRect(x,y,kind==='steel'?random()*12+1:random()*2+1,kind==='steel'?.5:random()*2+1);}
if(kind==='fabric'){for(let i=0;i<size;i+=3){ctx.fillStyle='rgba(30,30,30,.09)';ctx.fillRect(i,0,1,size);ctx.fillRect(0,i,size,1);}}
if(kind==='steel'){for(let i=0;i<20;i++){ctx.fillStyle='rgba(160,105,68,.12)';ctx.fillRect(random()*size,random()*size,random()*6+2,random()*3+1);}ctx.fillStyle='rgba(220,220,220,.22)';ctx.fillRect(0,0,size,2);ctx.fillRect(0,0,2,size);}
if(kind==='concrete'){for(let i=0;i<6;i++){const x=random()*size;ctx.strokeStyle='rgba(42,42,42,.13)';ctx.lineWidth=.6;ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x+random()*10-5,size);ctx.stroke();}}
const texture=new THREE.CanvasTexture(canvas);texture.colorSpace=THREE.SRGBColorSpace;texture.wrapS=texture.wrapT=THREE.RepeatWrapping;texture.anisotropy=2;surfaceTextures.set(kind,texture);return texture;}
function materialKind(color,metal){if(metal>=.3||[0x252e30,0x161c1d,0x747d7d,0x929b9d,0x596b66,0x98634b,0x697983,0x738e99,0x637267,0xad8e58,0x4e5c5e,0x6e797b,0x586466].includes(color))return 'steel';if([0x6b7964,0x877565,0x323d3e,0x546155,0x263132,0x5d5143,0x765038,0x725b42].includes(color))return 'fabric';return 'concrete';}
function makeBevelGeometry(){const shape=new THREE.Shape();shape.moveTo(-.45,-.45);shape.lineTo(.45,-.45);shape.lineTo(.45,.45);shape.lineTo(-.45,.45);shape.closePath();const geometry=new THREE.ExtrudeGeometry(shape,{depth:.9,bevelEnabled:true,bevelSegments:1,steps:1,bevelSize:.05,bevelThickness:.05});geometry.translate(0,0,-.45);geometry.computeVertexNormals();return geometry;}
const bevelGeo=makeBevelGeometry();const sharedGunGeometries=new Set([boxGeo,sphereGeo,cylinderGeo,bevelGeo]);
function bevelBox(group,x,y,z,w,h,d,color){const mesh=new THREE.Mesh(bevelGeo,mat(color,.25));mesh.position.set(x,y,z);mesh.scale.set(w,h,d);mesh.castShadow=true;mesh.receiveShadow=true;group.add(mesh);return mesh;}

let skyMaterial,skyMesh;const detailMaterialCache=new Map();
function initSky(){skyMesh=new THREE.Sky();skyMesh.scale.setScalar(450000);skyMesh.frustumCulled=false;skyMesh.renderOrder=-10;skyMaterial=skyMesh.material;scene.add(skyMesh);}
function updateSky(day,phase,theme){const u=skyMaterial.uniforms;u.turbidity.value=save.config.weather==='Dense fog'?12:save.config.weather==='Rain'?9:4;u.rayleigh.value=2.4;u.mieCoefficient.value=.006;u.mieDirectionalG.value=.82;u.sunPosition.value.set(Math.cos(phase*Math.PI*2),Math.sin(phase*Math.PI*2),.4).normalize().multiplyScalar(450000);skyMesh.position.copy(camera.position);}
function detailMaterial(text,hazard=false){const key=text+'_'+hazard;if(detailMaterialCache.has(key))return detailMaterialCache.get(key);const canvas=document.createElement('canvas');canvas.width=256;canvas.height=128;const ctx=canvas.getContext('2d');ctx.fillStyle=hazard?'#b49b50':'#ded9bf';ctx.fillRect(0,0,256,128);if(hazard){ctx.fillStyle='#202d2e';for(let x=-128;x<384;x+=48){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x+24,0);ctx.lineTo(x-104,128);ctx.lineTo(x-128,128);ctx.closePath();ctx.fill();}}else{ctx.fillStyle='#2a3a36';ctx.font='bold 33px sans-serif';ctx.fillText(text,15,59);ctx.font='16px monospace';ctx.fillText('FRONTLINE / LOGISTICS',15,96);ctx.strokeStyle='#6b7566';ctx.lineWidth=3;ctx.strokeRect(7,7,242,114);}const tex=new THREE.CanvasTexture(canvas);tex.colorSpace=THREE.SRGBColorSpace;const material=new THREE.MeshStandardMaterial({map:tex,roughness:.75,metalness:.06,side:THREE.DoubleSide});detailMaterialCache.set(key,material);return material;}
const decalGeo=new THREE.PlaneGeometry(1,1);let contactMaterial;
function addContactShadows(){if(!contactMaterial){const canvas=document.createElement('canvas');canvas.width=canvas.height=64;const ctx=canvas.getContext('2d'),grad=ctx.createRadialGradient(32,32,2,32,32,32);grad.addColorStop(0,'rgba(8,17,20,.36)');grad.addColorStop(.45,'rgba(8,17,20,.18)');grad.addColorStop(1,'rgba(8,17,20,0)');ctx.fillStyle=grad;ctx.fillRect(0,0,64,64);contactMaterial=new THREE.MeshBasicMaterial({map:new THREE.CanvasTexture(canvas),transparent:true,opacity:.68,depthWrite:false,alphaTest:.025});}const candidates=world.colliders.filter(c=>c.y1<.3&&c.y2>1&&c.x2-c.x1<15&&c.z2-c.z1<15).slice(0,90);const inst=new THREE.InstancedMesh(decalGeo,contactMaterial,candidates.length);const q=new THREE.Quaternion().setFromAxisAngle(new V(1,0,0),-Math.PI/2);for(let i=0;i<candidates.length;i++){const c=candidates[i],x=(c.x1+c.x2)/2,z=(c.z1+c.z2)/2;tmpPos.set(x,terrainHeight(x,z,world.theme)+.045,z);tmpScale.set(c.x2-c.x1+1.2,c.z2-c.z1+1.2,1);tmpMatrix.compose(tmpPos,q,tmpScale);inst.setMatrixAt(i,tmpMatrix);}inst.computeBoundingSphere();worldRoot.add(inst);}
function addWorldDetail(world,box,ground,theme,random){
function label(x,y,z,w,h,text,hazard=false,rotation=0){const m=new THREE.Mesh(decalGeo,detailMaterial(text,hazard));m.position.set(x,y,z);m.scale.set(w,h,1);m.rotation.y=rotation;worldRoot.add(m);}
const cylinders=new Map();function round(x,y,z,r,height,color,rotationZ=0,rotationX=0){let array=cylinders.get(color);if(!array)cylinders.set(color,array=[]);array.push([x,y,z,r,height,rotationZ,rotationX]);}
function truck(x,z){const y=ground(x,z);box(x,y+.8,z,2.7,.45,6.2,0x34423e);box(x,y+1.7,z+1.7,2.65,1.8,2.3,0x617064);box(x,y+1.65,z-1.7,2.65,1.65,3.5,0x718175);box(x,y+2.1,z+2.87,2.15,.68,.04,0x354c57,false);box(x,y+1.15,z+2.96,2.75,.22,.15,0x252e30,false);for(let sign of [-1,1]){box(x+sign*.85,y+1.4,z+2.95,.35,.2,.04,0xd8cb9d,false);for(let wz of [-2,1.9]){round(x+sign*1.38,y+.58,z+wz,.55,.30,0x252e30,Math.PI/2);round(x+sign*1.56,y+.58,z+wz,.27,.04,0x929b9d,Math.PI/2);}}label(x,y+1.8,z-3.47,1.5,.5,'FZ / SUPPLY',false,Math.PI);world.cover.push(new V(x+2,y,z));}
function barrels(x,z){const y=ground(x,z);for(let i=0;i<3;i++){const bx=x+(i-1)*.85,bz=z+(i%2)*.65;round(bx,y+.59,bz,.35,1.18,0x657976);round(bx,y+.2,bz,.365,.04,0x252e30);round(bx,y+.97,bz,.365,.04,0x252e30);world.colliders.push({x1:bx-.26,x2:bx+.26,y1:y,y2:y+1.15,z1:bz-.26,z2:bz+.26});}}
function rocks(x,z){const y=ground(x,z);for(let i=0;i<3;i++){const mesh=new THREE.Mesh(sphereGeo,mat(theme===4?0x91a5ae:0x8d8b79));mesh.position.set(x+(i-1)*.65,y+.6+i*.1,z+i*.4);mesh.scale.set(1.2,.8+i*.12,1);mesh.rotation.set(i*.4,i*.7,0);mesh.castShadow=true;worldRoot.add(mesh);}world.colliders.push({x1:x-.9,x2:x+.9,y1:y,y2:y+1.2,z1:z-.7,z2:z+1.0});}
// Anchored props along outer service lanes keep the central combat routes clear.
if(theme===0||theme===3||theme===4){truck(-37,-21);truck(37,22);barrels(-37,20);barrels(37,-20);}else{barrels(-30,5);barrels(30,-5);rocks(-32,-22);rocks(32,22);}
for(const z of [-24,-12,12,24])if(theme===0){label(-20,1.85,z+4.04,1.5,.5,'FZC 0047');label(21,1.85,z+4.04,1.5,.5,'FZC 0082');label(-10,.5,z+4.05,2.3,.20,'',true);label(11,.5,z+4.05,2.3,.20,'',true);}
for(const x of [-29,29])if(theme===0){label(x,3.2,-6.20,3,.8,x<0?'WAREHOUSE A':'WAREHOUSE B',false,Math.PI);for(let i=0;i<3;i++)round(x-4+i*3,4.85,1, .40,1.4,0x6e797b);}
for(const x of [-21,21])if(theme===3){label(x,3.25,-27.18,3,.7,'SECTOR 07',false,Math.PI);for(const z of [-18,18]){box(x+5.8,2,z,.12,3.5,2.7,0x4e5c5e,false);for(let h=.45;h<3.5;h+=.65)box(x+5.95,h,z,.22,.08,2.8,0x929b9d,false);}}
if(theme===1){label(-19,2.5,-22.2,3,.7,'OUTPOST 12',false,Math.PI);for(let x of [-27,27]){round(x,ground(x,26)+2.5,26,.1,5,0x929b9d);box(x,ground(x,26)+4.4,26,2,.08,.08,0x929b9d,false);}}
if(theme===4){label(-20,3.25,-9.2,4,.8,'POLAR RESEARCH',false,Math.PI);for(let x of [-24,-20,-16])box(x,4.65,0,2,.1,17,0xd8e4e5,false);}
if(theme===2){label(-17,2.7,-22.18,2.8,.65,'FIELD STATION',false,Math.PI);for(let z of [-30,30])rocks(29,z);}
for(const [color,arr] of cylinders){const inst=new THREE.InstancedMesh(cylinderGeo,mat(color,.35),arr.length);const euler=new THREE.Euler();for(let i=0;i<arr.length;i++){const a=arr[i];tmpPos.set(a[0],a[1],a[2]);tmpScale.set(a[3],a[4],a[3]);tmpQuat.setFromEuler(euler.set(a[6],0,a[5]));tmpMatrix.compose(tmpPos,tmpQuat,tmpScale);inst.setMatrixAt(i,tmpMatrix);}inst.castShadow=true;inst.receiveShadow=true;inst.computeBoundingSphere();worldRoot.add(inst);}tmpQuat.identity();}

function mat(color,metal=.1){const key=color+'_'+metal;if(!materials.has(key))materials.set(key,new THREE.MeshStandardMaterial({color,roughness:materialKind(color,metal)==='steel'?.52:materialKind(color,metal)==='fabric'?.96:.84,metalness:materialKind(color,metal)==='steel'?Math.max(.25,metal):.02,map:surfaceTexture(materialKind(color,metal)),bumpMap:surfaceTexture(materialKind(color,metal)),bumpScale:materialKind(color,metal)==='steel'?.004:.012}));return materials.get(key);}
function meshBox(group,x,y,z,w,h,d,color,shadow=true){const o=new THREE.Mesh(boxGeo,mat(color));o.position.set(x,y,z);o.scale.set(w,h,d);o.castShadow=shadow;o.receiveShadow=true;group.add(o);return o;}
function cylinder(group,x,y,z,r,h,color,rot=0){const o=new THREE.Mesh(cylinderGeo,mat(color,.35));o.position.set(x,y,z);o.scale.set(r,h,r);o.rotation.z=rot;o.castShadow=true;group.add(o);return o;}
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('show'),2600);}
function fatal(e){console.error(e);$('#fatal').hidden=false;$('#fatal p').textContent=e.message||String(e);}
try{renderer=new THREE.WebGLRenderer({antialias:false,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5)*renderScale);renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.24;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;$('#viewport').appendChild(renderer.domElement);
scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(save.settings.fov,innerWidth/innerHeight,.06,180);camera.rotation.order='YXZ';scene.add(camera);sun=new THREE.DirectionalLight(0xffdfb3,2.8);sun.position.set(-20,35,18);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);sun.shadow.camera.left=-35;sun.shadow.camera.right=35;sun.shadow.camera.top=35;sun.shadow.camera.bottom=-35;sun.shadow.camera.far=120;sun.shadow.bias=-.001;sun.shadow.normalBias=.02;scene.add(sun);hemi=new THREE.HemisphereLight(0xcbdfe7,0x554d40,2);scene.add(hemi);weaponRoot=new THREE.Group();camera.add(weaponRoot);initSky();bloom=typeof FZBloom==='function'?new FZBloom(renderer):null;
}catch(e){fatal(new Error('WebGL could not start. Try a WebGL-capable browser and enable hardware acceleration. '+e.message));return;}
// Cached noise and impulse response; every gunshot has a transient, body, mechanism and tail.
const AudioManager={ctx:null,noise:null,reverb:null,init(){try{if(!this.ctx){const c=this.ctx=new(window.AudioContext||window.webkitAudioContext)();const random=rng(917);this.noise=c.createBuffer(1,c.sampleRate,c.sampleRate);const n=this.noise.getChannelData(0);for(let i=0;i<n.length;i++)n[i]=random()*2-1;const impulse=c.createBuffer(2,c.sampleRate*.55|0,c.sampleRate);for(let ch=0;ch<2;ch++){const a=impulse.getChannelData(ch);for(let i=0;i<a.length;i++)a[i]=(random()*2-1)*Math.pow(1-i/a.length,4);}this.reverb=c.createConvolver();this.reverb.buffer=impulse;const gain=c.createGain();gain.gain.value=.12;this.reverb.connect(gain);gain.connect(c.destination);}this.ctx.resume();}catch(e){}},
play(type,distance=0,weapon=null){if(!this.ctx||this.ctx.state!=='running')return;const c=this.ctx,t=c.currentTime,vol=save.settings.volume/(1+distance*.08),shot=type==='shot'||type==='sniper',kind=weapon?.type||'rifle';const profile=kind==='sniper'?[58,.8,1350]:kind==='shotgun'?[74,.6,1700]:kind==='smg'?[135,.23,2900]:kind==='pistol'?[145,.27,3400]:kind==='lmg'?[80,.42,1900]:[104,.36,2400];const duration=shot?profile[1]:type==='boom'?.8:type==='step'?.09:.08;const bus=c.createGain();bus.gain.value=vol;bus.connect(c.destination);if(shot||type==='boom')bus.connect(this.reverb);
const noise=c.createBufferSource();noise.buffer=this.noise;const filter=c.createBiquadFilter();filter.type='lowpass';filter.frequency.setValueAtTime(shot?profile[2]:type==='boom'?550:type==='step'?320:5000,t);filter.frequency.exponentialRampToValueAtTime(shot?450:110,t+duration);const envelope=c.createGain();envelope.gain.setValueAtTime(shot?.55:type==='boom'?.6:type==='step'?.08:.04,t);envelope.gain.exponentialRampToValueAtTime(.0001,t+duration);noise.connect(filter);filter.connect(envelope);envelope.connect(bus);noise.start(t);noise.stop(t+duration);
const body=c.createOscillator(),gain=c.createGain();body.type='sine';body.frequency.setValueAtTime(shot?profile[0]:type==='boom'?48:type==='hit'?1200:180,t);body.frequency.exponentialRampToValueAtTime(shot?30:40,t+duration);gain.gain.setValueAtTime(shot?.35:type==='hit'?.055:.025,t);gain.gain.exponentialRampToValueAtTime(.0001,t+duration*.8);body.connect(gain);gain.connect(bus);body.start(t);body.stop(t+duration);
// Mechanical closure follows the report; distinct bolt delay for sniper/pump action.
if(shot){const click=c.createBufferSource(),cg=c.createGain(),hp=c.createBiquadFilter();click.buffer=this.noise;hp.type='highpass';hp.frequency.value=4000;cg.gain.setValueAtTime(.025*vol,t+(kind==='sniper'||kind==='shotgun'?.23:.055));cg.gain.exponentialRampToValueAtTime(.0001,t+(kind==='sniper'||kind==='shotgun'?.29:.09));click.connect(hp);hp.connect(cg);cg.connect(c.destination);click.start(t+(kind==='sniper'||kind==='shotgun'?.23:.055));click.stop(t+.32);}
noise.onended=()=>{noise.disconnect();filter.disconnect();envelope.disconnect();body.disconnect();gain.disconnect();bus.disconnect();};}};
function makeGun(id,third=false){const w=WEAPONS[id],g=new THREE.Group(),metal=0x252e30,body=w.color;const pistol=w.type==='pistol',sniper=w.type==='sniper',smg=w.type==='smg',shotgun=w.type==='shotgun',lmg=w.type==='lmg';
bevelBox(g,0,0,0,pistol?.09:.12,.13,pistol?.25:.43,body);bevelBox(g,0,-.11,.07,.075,.22,.10,metal).rotation.x=-.25;
meshBox(g,0,-.115,-.055,lmg?.16:.07,lmg?.19:.26,.11,metal).rotation.x=id===1?-.2:.05;
bevelBox(g,0,.035,-.3,.095,.09,pistol?.1:sniper?.37:.27,body);
const barrel=cylinder(g,0,.015,pistol?-.2:sniper?-.65:shotgun?-.55:-.48,.018,sniper?.48:shotgun?.35:.25,metal);barrel.rotation.x=Math.PI/2;
if(!pistol){meshBox(g,0,-.005,.32,.085,.14,.29,id===1?0x765038:body);meshBox(g,0,.08,-.05,.10,.025,.44,metal);for(let i=0;i<6;i++)meshBox(g,0,.097,-.22+i*.045,.105,.01,.018,0x747d7d,false);meshBox(g,0,.02,-.25,.125,.025,.20,metal);}
if(shotgun){const tube=cylinder(g,0,-.045,-.47,.025,.35,metal);tube.rotation.x=Math.PI/2;meshBox(g,0,-.015,-.32,.13,.1,.16,0x725b42);}
if(smg){meshBox(g,.03,-.075,.12,.11,.10,.2,body);meshBox(g,0,-.10,-.2,.055,.14,.06,metal);}
if(lmg){meshBox(g,.08,-.06,0,.18,.20,.18,0x5f624e);for(let i=0;i<6;i++)cylinder(g,.1+i*.03,.015,.02,.012,.055,0xaa9258,Math.PI/2);}
const optic=save.loadout.attachment,scoped=sniper||optic==='4x scope',sightY=scoped?.17:pistol?.095:optic==='Red dot'?.155:.125;
g.userData.sightY=sightY;g.userData.scoped=scoped;
if(scoped){const tube=new THREE.Mesh(new THREE.CylinderGeometry(.052,.052,sniper?.28:.18,16,1,true),mat(metal,.7));tube.rotation.x=Math.PI/2;tube.position.set(0,sightY,-.10);g.add(tube);meshBox(g,0,.10,-.10,.065,.065,.1,metal);cylinder(g,.06,sightY,-.08,.024,.035,metal,Math.PI/2);}
else if(optic==='Red dot'&&!pistol){for(const sign of [-1,1])meshBox(g,sign*.033,sightY,-.1,.009,.069,.055,metal);meshBox(g,0,sightY+.035,-.1,.075,.009,.055,metal);meshBox(g,0,sightY-.035,-.1,.075,.009,.055,metal);const dot=new THREE.Mesh(new THREE.SphereGeometry(.0018,8,6),new THREE.MeshBasicMaterial({color:0xff3424,toneMapped:false,depthTest:false}));dot.position.set(0,sightY,-.13);dot.renderOrder=20;g.add(dot);g.userData.dot=dot;dot.visible=false;}
else{for(const sign of [-1,1])meshBox(g,sign*.017,sightY,-.015,.012,.035,.024,metal);meshBox(g,0,sightY-.016,-.015,.045,.008,.025,metal);meshBox(g,0,sightY-.012,pistol?-.20:-.46,.008,.03,.015,metal);}
if(optic==='Suppressor'){const s=cylinder(g,0,.015,-.66,.03,.19,0x33393b);s.rotation.x=Math.PI/2;}
meshBox(g,.066,.03,.03,.012,.055,.09,0x161c1d);for(let i=0;i<3;i++)meshBox(g,.066,-.02+i*.03,-.08,.009,.008,.008,0x929b9d,false);
if(!third){const trigger=meshBox(g,.025,-.075,.015,.012,.07,.018,0x929b9d);trigger.rotation.x=.28;for(const sign of [-1,1]){meshBox(g,sign*.043,-.18,.005,.008,.012,.10,metal);meshBox(g,sign*.043,-.14,-.046,.008,.08,.012,metal);}for(let i=0;i<5;i++)meshBox(g,.065,.02,-.35+i*.026,.004,.029,.016,0x161c1d);const hand=bevelBox(g,.07,-.19,.12,.11,.105,.15,0x323d3e);hand.rotation.x=-.35;bevelBox(g,-.075,-.13,-.29,.12,.105,.16,0x323d3e).rotation.z=.15;bevelBox(g,.08,-.24,.24,.10,.12,.15,0x6b7964);bevelBox(g,-.105,-.19,-.21,.10,.11,.12,0x6b7964);const flashMat=new THREE.MeshBasicMaterial({color:0xffd69a,toneMapped:false,transparent:true,opacity:.92,depthWrite:false,blending:THREE.AdditiveBlending});const flashMesh=new THREE.Mesh(new THREE.ConeGeometry(.05,.19,5),flashMat);flashMesh.rotation.x=-Math.PI/2;flashMesh.position.set(0,.015,sniper?-.96:shotgun?-.77:pistol?-.37:-.71);flashMesh.visible=false;g.add(flashMesh);g.userData.muzzle=flashMesh;g.userData.flashLife=0;g.userData.firstPerson=true;addGunDetail(g,id);}if(third)g.scale.setScalar(.9);return g;}
function addGunDetail(g,id){const metal=0x252e30,w=WEAPONS[id],pistol=w.type==='pistol';g.userData.magazine=g.children[2];g.userData.magazineY=g.children[2].position.y;
// Receiver pins, rail teeth, side ventilation, charging handle and stamped seams.
for(const side of [-1,1]){for(let i=0;i<4;i++){const pin=cylinder(g,side*.063,.035-i*.022,.055,.006,.009,0x929b9d,Math.PI/2);pin.castShadow=false;}meshBox(g,side*.063,.04,-.035,.005,.014,.075,0x161c1d,false);if(!pistol)for(let i=0;i<7;i++)meshBox(g,side*.05,.043,-.4+i*.024,.003,.025,.01,0x12191a,false);}
meshBox(g,.084,.06,.045,.045,.012,.024,metal,false);if(id===1){const magazine=g.userData.magazine;magazine.rotation.x=-.18;for(let i=0;i<5;i++)meshBox(g,.037,-.12-i*.03,-.055+i*.008,.003,.024,.09,0x515a50,false);meshBox(g,0,-.006,.32,.10,.14,.22,0x825f40);}
if(id===2){meshBox(g,0,-.13,.08,.14,.18,.15,metal);meshBox(g,0,.01,.4,.035,.03,.22,metal);}
if(id===3){for(const sign of [-1,1]){const leg=meshBox(g,sign*.07,-.15,-.5,.012,.24,.015,metal);leg.rotation.z=sign*.35;}meshBox(g,.09,.03,.13,.07,.013,.025,0x929b9d);}
if(id===4){for(let i=0;i<6;i++)meshBox(g,0,-.009,-.4+i*.023,.135,.009,.008,0x252e30,false);}
if(id===7){const drum=cylinder(g,0,-.018,-.09,.064,.115,0x7b8587);drum.rotation.x=Math.PI/2;for(let i=0;i<6;i++){const a=i*Math.PI/3;const flute=cylinder(g,Math.cos(a)*.047,-.018+Math.sin(a)*.047,-.09,.011,.119,metal);flute.rotation.x=Math.PI/2;}meshBox(g,0,-.14,.09,.08,.20,.10,0x715340);}
}
function makeCharacter(team=1){const g=new THREE.Group(),uniform=team===0?0x6b7964:0x877565,armor=0x323d3e;bevelBox(g,0,1.03,0,.43,.58,.28,uniform);meshBox(g,0,1.13,-.16,.39,.40,.1,armor);for(let i=0;i<3;i++)meshBox(g,-.12+i*.12,1.05,-.23,.095,.15,.06,0x546155);meshBox(g,0,.73,0,.38,.12,.28,armor);meshBox(g,0,1.19,.23,.32,.39,.15,armor);
bevelBox(g,0,1.51,0,.24,.27,.23,0xb09981);const h=bevelBox(g,0,1.66,0,.30,.17,.29,uniform);meshBox(g,0,1.52,-.13,.24,.06,.035,0x202b2b);meshBox(g,0,1.40,0,.13,.09,.14,0xa59078);
const legs=[],arms=[];for(const sign of [-1,1]){const leg=new THREE.Group();leg.position.set(sign*.11,.73,0);meshBox(leg,0,-.19,0,.16,.35,.17,uniform);meshBox(leg,0,-.40,-.05,.16,.13,.09,armor);meshBox(leg,0,-.49,.015,.13,.25,.14,uniform);meshBox(leg,0,-.67,-.045,.17,.14,.26,0x263132);g.add(leg);legs.push(leg);const arm=new THREE.Group();arm.position.set(sign*.27,1.3,0);meshBox(arm,0,-.14,0,.16,.28,.16,uniform);meshBox(arm,0,-.32,-.11,.12,.27,.13,uniform).rotation.x=-.55;meshBox(arm,0,-.44,-.22,.12,.11,.12,armor);g.add(arm);arms.push(arm);}
const gun=makeGun(team===0?0:1,true);gun.position.set(.1,.99,-.36);g.add(gun);g.userData={legs,arms,gun};return g;}
function disposeWorld(){if(worldRoot){scene.remove(worldRoot);worldRoot.traverse(o=>{if(o.isInstancedMesh)o.dispose();if(o.isMesh&&!o.isInstancedMesh&&o.geometry!==boxGeo&&o.geometry!==cylinderGeo&&o.geometry!==bevelGeo&&o.geometry!==decalGeo&&o.material&&!Array.from(materials.values()).includes(o.material)&&!Array.from(detailMaterialCache.values()).includes(o.material))o.material.dispose();if(o.geometry&&o.geometry!==boxGeo&&o.geometry!==sphereGeo&&o.geometry!==cylinderGeo&&o.geometry!==bevelGeo&&o.geometry!==decalGeo)o.geometry.dispose();});}for(const b of bots)scene.remove(b.mesh);bots=[];if(preview)scene.remove(preview);}
function terrainHeight(x,z,theme){if(theme===0||theme===3)return 0;const edge=clamp((Math.max(Math.abs(x),Math.abs(z))-25)/15,0,1);return (Math.sin(x*.10)*Math.cos(z*.12)*1.7+Math.sin(z*.21+x*.04)*.6)*edge;}
function buildWorld(theme,seed){disposeWorld();const random=rng(seed);worldRoot=new THREE.Group();scene.add(worldRoot);world={theme,seed,colliders:[],surfaces:[],cover:[],spawns:[],batches:new Map(),nav:null};const t=THEMES[theme];scene.background=new THREE.Color(t.sky);scene.fog=new THREE.Fog(t.fog,38,save.settings.quality==='Ultra Low'?75:155);
function box(x,y,z,w,h,d,color,solid=true){const key=color;let batch=world.batches.get(key);if(!batch)world.batches.set(key,batch=[]);batch.push([x,y,z,w,h,d]);if(solid)world.colliders.push({x1:x-w/2,x2:x+w/2,y1:y-h/2,y2:y+h/2,z1:z-d/2,z2:z+d/2});return batch;}
function ground(x,z){return terrainHeight(x,z,theme);}
for(let cz=-44;cz<44;cz+=22)for(let cx=-44;cx<44;cx+=22){const geom=new THREE.PlaneGeometry(22,22,11,11);geom.rotateX(-Math.PI/2);const p=geom.attributes.position,colors=new Float32Array(p.count*3);for(let i=0;i<p.count;i++){const x=p.getX(i)+cx+11,z=p.getZ(i)+cz+11;p.setY(i,ground(x,z));const patch=Math.sin(x*.24+Math.sin(z*.15))*Math.cos(z*.21);const c=new THREE.Color(t.ground).multiplyScalar(.78+patch*.10+random()*.12);colors[i*3]=c.r;colors[i*3+1]=c.g;colors[i*3+2]=c.b;}geom.setAttribute('color',new THREE.BufferAttribute(colors,3));for(let i=0;i<geom.attributes.uv.count;i++){geom.attributes.uv.setXY(i,geom.attributes.uv.getX(i)*7,geom.attributes.uv.getY(i)*7);}geom.computeVertexNormals();const m=new THREE.Mesh(geom,new THREE.MeshStandardMaterial({vertexColors:true,roughness:.95,map:surfaceTexture('soil'),bumpMap:surfaceTexture('soil'),bumpScale:.07}));m.position.set(cx+11,0,cz+11);m.receiveShadow=true;worldRoot.add(m);}
// Deliberate three-lane layout. Clear perimeter paths connect all spawn quadrants.
box(0,.012,0,7,.025,84,theme===1?0xa78a60:0x62686a,false);box(0,.017,0,84,.03,6,theme===1?0xa78a60:0x62686a,false);
for(let z=-38;z<=38;z+=7)box(0,.036,z,.12,.02,2,0xcac3a0,false);
function container(x,z,length,color,open=false){const y=ground(x,z);if(open){box(x-1.35,y+1.3,z,.18,2.6,length,color);box(x+1.35,y+1.3,z,.18,2.6,length,color);box(x,y+2.65,z,2.9,.15,length,color);box(x,y+.08,z,2.9,.16,length,0x484f4d);}else box(x,y+1.3,z,2.8,2.6,length,color);
for(let s=-1;s<=1;s+=2){for(let i=-length/2+.3;i<length/2;i+=.4)box(x+s*1.43,y+1.3,z+i,.055,2.45,.055,color,false);box(x+s*1.33,y+1.3,z-length/2,.11,2.7,.12,0x4a5150,false);box(x+s*1.33,y+1.3,z+length/2,.11,2.7,.12,0x4a5150,false);}if(!open){for(let s of [-1,1])box(x+s*.52,y+1.3,z+length/2+.025,.055,2.2,.04,0xb1b4a7,false);}world.cover.push(new V(x+2.3,y,z));}
function building(x,z,w,d,h,color){const y=ground(x,z),door=2.4;box(x-w/2,y+h/2,z,.3,h,d,color);box(x+w/2,y+h/2,z,.3,h,d,color);for(let s of [-1,1]){box(x-(w+door)/4,y+h/2,z+s*d/2,(w-door)/2,h,.3,color);box(x+(w+door)/4,y+h/2,z+s*d/2,(w-door)/2,h,.3,color);box(x,y+(h+2.5)/2,z+s*d/2,door,h-2.5,.3,color);}box(x,y+h+.12,z,w+.6,.24,d+.6,0x4e5c5e);box(x,y+.02,z,w,.04,d,0x777c75,false);for(let a=-w/2+1;a<w/2;a+=2){box(x+a,y+h*.65,z-d/2-.17,1,.8,.02,0x43606a,false);box(x+a,y+h*.65,z+d/2+.17,1,.8,.02,0x43606a,false);}box(x+.5,y+h+.7,z,1.7,1.1,1.3,0x6e797b);
// Continuous collision ramp under visible stairs, avoiding per-step bounce.
const sx=x+w/2+1.4,sz=z-d/2;for(let i=0;i<16;i++)box(sx,y+(i+1)*h/16/2,sz+i*.42,2,(i+1)*h/16,.42,0x6f7877,false);world.surfaces.push({x1:sx-1,x2:sx+1,z1:sz,z2:sz+6.72,base:y,height:h,axis:'z'});box(sx,y+h,sz+6.8,2,.12,1.2,0x586466);box(x+w/2+.1,y+h,z+d/2-.2,2.5,.16,1.8,0x586466);world.cover.push(new V(x-w/2-1,y,z));}
if(theme===0){for(let z of [-24,-12,12,24])for(let x of [-20,-10,11,21])container(x,z,8,[0x596b66,0x98634b,0x697983][Math.floor(random()*3)],(x===11||x===-10)&&Math.abs(z)===12);building(-29,1,11,14,4,0x969286);building(29,1,11,14,4,0x8b9188);for(let x of [-31,31]){box(x,7,-32,1,14,1,0xad8e58);box(x-5,13,-32,12,.65,.65,0xad8e58);box(x-10,10,-32,.08,6,.08,0x343d3e,false);}}
if(theme===1){for(let x of [-19,19])for(let z of [-18,18])building(x,z,8,8,3.2,0xa5967c);for(let i=0;i<22;i++){let x=(random()-.5)*74,z=(random()-.5)*74;if(Math.abs(x)<7||Math.abs(z)<7)continue;const y=ground(x,z);box(x,y+.9,z,2+random()*3,1.8,2+random()*2,0x938772);world.cover.push(new V(x+3,y,z));}for(let z of [-10,10])for(let x of [-12,12])box(x,1,z,5,2,.8,0xaaa18b);box(32,6,-26,.6,12,.6,0x616c6b);cylinder(worldRoot,32,12,-26,2,.2,0x858d81).rotation.z=.55;}
if(theme===2){building(-17,-17,9,10,3.4,0x807e65);building(18,17,11,10,4,0x7c8780);container(-16,18,7,0x637267,true);container(18,-16,7,0x6d7864,true);for(let i=0;i<65;i++){const x=(random()-.5)*84,z=(random()-.5)*84;if(Math.abs(x)<8||Math.abs(z)<7||Math.abs(Math.abs(x)-17)<7&&Math.abs(Math.abs(z)-17)<8)continue;const y=ground(x,z),h=5+random()*4;box(x,y+h/2,z,.4,h,.4,0x5d5143);const tree=new THREE.Mesh(new THREE.ConeGeometry(1.8,h*.75,5),mat(0x344d3c));tree.position.set(x,y+h*.78,z);tree.castShadow=true;worldRoot.add(tree);}box(0,.12,26,7,.24,7,0x77705b,false);for(let s of [-1,1])box(s*3.2,1,26,.1,1.8,7,0x746b53);}
if(theme===3){for(let x of [-21,21])for(let z of [-21,0,21])building(x,z,12,12,z===0?6:4.2,[0x8a8f8b,0x8b8175,0x6d7b80][Math.floor(random()*3)]);for(let x of [-8,8])for(let z of [-30,0,30]){box(x,2.8,z,.12,5.6,.12,0x4a5559);box(x+.6,5.5,z,1.2,.1,.35,0xdbc493,false);}for(let z of [-14,14])box(0,.65,z,5,1.3,.5,0xa8a89a);}
if(theme===4){building(-20,0,12,18,4.5,0x829598);building(21,-19,12,10,3.5,0x829598);building(21,20,12,10,3.5,0x748e97);for(let z of [-22,22])for(let x of [-8,7])container(x,z,8,0x738e99,x===7);for(let z of [-10,10])for(let x of [-8,9])box(x,.8,z,5,1.6,1,0xd0dfdf);box(-28,10,-28,.6,20,.6,0x617780);for(let i=2;i<16;i+=4)box(-28,i,-28,3,.15,.15,0x617780);}
for(let x of [-34,-7,7,34])for(let z of [-34,-7,7,34]){if(Math.abs(x)===7&&Math.abs(z)===7)continue;box(x,ground(x,z)+.55,z,1.4,1.1,1.4,0x74725d);for(let s of [-.5,.5])box(x+s,ground(x,z)+.57,z, .08,1.16,1.5,0x484f48,false);world.cover.push(new V(x+1.5,ground(x,z),z));}
for(let s of [-1,1]){box(s*44,1,0,.5,4,88,0x556365);box(0,1,s*44,88,4,.5,0x556365);}
addWorldDetail(world,box,ground,theme,random);
for(const [color,arr] of world.batches){const material=mat(color);const inst=new THREE.InstancedMesh(boxGeo,material,arr.length);for(let i=0;i<arr.length;i++){const a=arr[i];tmpPos.set(a[0],a[1],a[2]);tmpScale.set(a[3],a[4],a[5]);tmpMatrix.compose(tmpPos,tmpQuat,tmpScale);inst.setMatrixAt(i,tmpMatrix);}inst.castShadow=arr.some(a=>a[4]>1&&a[3]>.3);inst.receiveShadow=true;inst.computeBoundingSphere();worldRoot.add(inst);}
addContactShadows();
for(let z of [-36,36])for(let x of [-32,-16,0,16,32])world.spawns.push(new V(x,ground(x,z),z));buildNav();preview=makeCharacter(0);preview.position.set(0,0,13);scene.add(preview);applyQuality();return world;}
function floorAt(x,z,feet=0){let y=terrainHeight(x,z,world.theme);for(const s of world.surfaces)if(x>=s.x1&&x<=s.x2&&z>=s.z1&&z<=s.z2)y=Math.max(y,s.base+clamp((z-s.z1)/(s.z2-s.z1),0,1)*s.height);for(const c of world.colliders)if(x>c.x1-.05&&x<c.x2+.05&&z>c.z1-.05&&z<c.z2+.05&&feet>=c.y2-.4)y=Math.max(y,c.y2);return y;}
function blocked(x,z,y,height=1.7,r=.34){for(const c of world.colliders)if(x+r>c.x1&&x-r<c.x2&&z+r>c.z1&&z-r<c.z2&&y+height>c.y1+.02&&y<c.y2-.3)return c;return null;}
function moveBody(body,dt,height=1.7){const pos=body.pos,vel=body.vel,oldY=pos.y;let nx=pos.x+vel.x*dt,nz=pos.z+vel.z*dt;const fx=floorAt(nx,pos.z,pos.y);if(!blocked(nx,pos.z,Math.max(pos.y,fx),height)&&fx<=pos.y+.42)pos.x=nx;else vel.x=0;const fz=floorAt(pos.x,nz,pos.y);if(!blocked(pos.x,nz,Math.max(pos.y,fz),height)&&fz<=pos.y+.42)pos.z=nz;else vel.z=0;vel.y-=22*dt;pos.y+=vel.y*dt;const ground=floorAt(pos.x,pos.z,oldY);body.grounded=pos.y<=ground+.04&&vel.y<=0;if(body.grounded){pos.y=ground;vel.y=0;}if(vel.y>0&&blocked(pos.x,pos.z,pos.y,height)){pos.y=oldY;vel.y=0;}pos.x=clamp(pos.x,-43.3,43.3);pos.z=clamp(pos.z,-43.3,43.3);if(pos.y<-10){pos.y=terrainHeight(pos.x,pos.z,world.theme);vel.y=0;}}
function rayBox(o,d,c,max=Infinity){let near=0,far=max;for(const [axis,a,b] of [['x','x1','x2'],['y','y1','y2'],['z','z1','z2']]){if(Math.abs(d[axis])<1e-8){if(o[axis]<c[a]||o[axis]>c[b])return Infinity;}else{let t1=(c[a]-o[axis])/d[axis],t2=(c[b]-o[axis])/d[axis];if(t1>t2)[t1,t2]=[t2,t1];near=Math.max(near,t1);far=Math.min(far,t2);if(near>far)return Infinity;}}return near;}
function wallDistance(o,d,max){let dist=max;for(const c of world.colliders)dist=Math.min(dist,rayBox(o,d,c,dist));return dist;}
const rayDir=new V(),rayOrigin=new V();function visible(a,b,smoke=true){rayDir.copy(b).sub(a);const dist=rayDir.length();rayDir.multiplyScalar(1/(dist||1));if(wallDistance(a,rayDir,dist-.2)<dist-.2)return false;if(smoke)for(const s of smokes){const vx=s.pos.x-a.x,vz=s.pos.z-a.z,along=vx*rayDir.x+vz*rayDir.z;if(along>0&&along<dist&&Math.hypot(a.x+rayDir.x*along-s.pos.x,a.z+rayDir.z*along-s.pos.z)<s.radius)return false;}return true;}
function buildNav(){const size=43,step=2,walk=new Uint8Array(size*size);for(let z=0;z<size;z++)for(let x=0;x<size;x++)walk[z*size+x]=blocked((x-21)*step,(z-21)*step,terrainHeight((x-21)*step,(z-21)*step,world.theme),1.7,.5)?0:1;world.nav={size,step,walk};}
function navIndex(x,z){return clamp(Math.round(z/2)+21,0,42)*43+clamp(Math.round(x/2)+21,0,42);}
function pathTo(from,to){const n=world.nav,start=navIndex(from.x,from.z),end=navIndex(to.x,to.z);if(start===end)return [];const parent=new Int16Array(n.walk.length);parent.fill(-1);const queue=new Int16Array(n.walk.length);let h=0,t=0;queue[t++]=start;parent[start]=start;let found=false;while(h<t){const p=queue[h++];if(p===end){found=true;break;}const x=p%43,z=p/43|0;for(const off of [-1,1,-43,43]){const q=p+off;if(q<0||q>=n.walk.length||Math.abs(q%43-x)>1||Math.abs((q/43|0)-z)>1||!n.walk[q]||parent[q]!==-1)continue;parent[q]=p;queue[t++]=q;}}if(!found)return [];const path=[];let p=end;while(p!==start&&path.length<300){path.push(new V((p%43-21)*2,0,((p/43|0)-21)*2));p=parent[p];}path.reverse();return path;}
const particlePool=[];for(let i=0;i<70;i++){const m=new THREE.Mesh(sphereGeo,new THREE.MeshBasicMaterial({color:0xe7b36f}));m.visible=false;scene.add(m);particlePool.push({mesh:m,pos:m.position,vel:new V(),life:0});}let particleCursor=0;
function burst(pos,count=7,color=0xd9bd88,force=3){count=Math.min(count,save.settings.quality==='Ultra Low'?4:save.settings.quality==='Low'?8:20);for(let i=0;i<count;i++){const p=particlePool[particleCursor++%particlePool.length];p.pos.copy(pos);p.vel.set((Math.random()-.5)*force,Math.random()*force,(Math.random()-.5)*force);p.life=.3+Math.random()*.35;p.mesh.material.color.setHex(color);p.mesh.scale.setScalar(.03+Math.random()*.035);p.mesh.visible=true;}}
const tracers=[];for(let i=0;i<16;i++){const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.BufferAttribute(new Float32Array(6),3));const m=new THREE.Line(g,new THREE.LineBasicMaterial({color:0xe9c587}));m.visible=false;scene.add(m);tracers.push({mesh:m,life:0});}let tracerCursor=0;
function tracer(a,b){const t=tracers[tracerCursor++%tracers.length],p=t.mesh.geometry.attributes.position;p.setXYZ(0,a.x,a.y,a.z);p.setXYZ(1,b.x,b.y,b.z);p.needsUpdate=true;t.life=.055;t.mesh.visible=true;}
const grenades=[],smokes=[];const grenadeMeshes=[];for(let i=0;i<12;i++){const m=new THREE.Mesh(sphereGeo,mat(0x57634e));m.scale.setScalar(.12);m.visible=false;scene.add(m);grenadeMeshes.push(m);}function throwGrenade(){if(!player.alive||player.grenades<=0)return;const mesh=grenadeMeshes.find(m=>!m.visible);if(!mesh)return;const d=new V(-Math.sin(yaw)*Math.cos(pitch),Math.sin(pitch),-Math.cos(yaw)*Math.cos(pitch));const pos=player.pos.clone().add(new V(0,1.35,0)).addScaledVector(d,.7);mesh.visible=true;mesh.position.copy(pos);grenades.push({mesh,pos,vel:d.multiplyScalar(15).add(new V(0,4,0)),fuse:2.2,type:player.throwType});player.grenades--;AudioManager.play('click');}
function explode(g){const pos=g.pos;burst(pos,20,g.type==='Frag'?0xe7a46b:0xe6e8dc,8);AudioManager.play('boom',player.pos.distanceTo(pos));if(g.type==='Smoke'){const group=new THREE.Group();const material=new THREE.MeshBasicMaterial({color:0xabb0a6,transparent:true,opacity:.22,depthWrite:false});for(let i=0;i<8;i++){const m=new THREE.Mesh(sphereGeo,material);m.position.set(Math.sin(i*2)*1.6,.4+i%3*.5,Math.cos(i*2)*1.6);m.scale.setScalar(2);group.add(m);}group.position.copy(pos);scene.add(group);smokes.push({pos:pos.clone(),group,material,radius:0,life:14});return;}
for(const target of [player,...bots]){if(!target.alive)continue;const eye=target.pos.clone().add(new V(0,1.2,0)),dist=eye.distanceTo(pos);if(dist>(g.type==='Frag'?9:18)||!visible(pos,eye,false))continue;if(g.type==='Frag'){const damage=110*(1-dist/9);if(target===player)damagePlayer(damage,pos);else damageBot(target,damage,false,dist,true);}else{if(target===player){const d=pos.clone().sub(eye).normalize(),look=new V(-Math.sin(yaw),0,-Math.cos(yaw));flash=clamp((1-dist/18)*Math.max(.15,d.dot(look)),0,1)*3;}else target.blind=3*(1-dist/18);}}
shake=Math.max(shake,.15);}
function updateGrenades(dt){for(let i=grenades.length-1;i>=0;i--){const g=grenades[i];g.fuse-=dt;g.vel.y-=16*dt;const next=g.pos.clone().addScaledVector(g.vel,dt);if(blocked(next.x,next.z,next.y,.2,.12)){g.vel.x*=-.55;g.vel.z*=-.55;}else{g.pos.x=next.x;g.pos.z=next.z;}g.pos.y=next.y;const floor=floorAt(g.pos.x,g.pos.z,g.pos.y)+.13;if(g.pos.y<floor){g.pos.y=floor;g.vel.y=Math.abs(g.vel.y)*.42;g.vel.x*=.75;g.vel.z*=.75;}g.mesh.position.copy(g.pos);if(g.fuse<=0){explode(g);g.mesh.visible=false;grenades.splice(i,1);}}for(let i=smokes.length-1;i>=0;i--){const s=smokes[i];s.life-=dt;s.radius=Math.min(4,s.radius+dt*2);s.group.scale.setScalar(Math.max(.01,s.radius/4));s.material.opacity=.23*clamp(s.life/3,0,1);if(s.life<=0){scene.remove(s.group);s.material.dispose();smokes.splice(i,1);}}}
function getWeaponId(){if(match?.mode==='Sniper Only')return 3;if(match?.mode==='Gun Game')return [0,2,1,4,5,6,7,3][Math.min(player.tier,7)];return player.slot===0?save.loadout.primary:save.loadout.secondary;}
function weaponStats(){const w=WEAPONS[getWeaponId()],a=save.loadout.attachment;return {...w,mag:w.mag+(a==='Extended mag'?Math.ceil(w.mag*.3):0),spread:w.spread*(a==='Vertical grip'?.8:1),recoil:w.recoil*(a==='Compensator'?.7:1)};}
function setGun(refill=false){if(gun){gun.traverse(o=>{if(o.geometry&&!sharedGunGeometries.has(o.geometry))o.geometry.dispose();if(o.material&&!Array.from(materials.values()).includes(o.material))o.material.dispose();});weaponRoot.remove(gun);}gun=makeGun(getWeaponId());weaponRoot.add(gun);weaponRoot.visible=appState==='game';if(refill)player.ammo[player.slot]=weaponStats().mag;player.reload=0;player.fireCooldown=.18;}
function switchWeapon(){if(match?.mode==='Sniper Only'||match?.mode==='Gun Game')return;player.slot=1-player.slot;setGun();AudioManager.play('click');}
function reload(){const w=weaponStats();if(player.reload||!player.alive||player.ammo[player.slot]>=w.mag)return;player.reload=w.reload;AudioManager.play('click');}
const bulletOrigin=new V(),bulletDirection=new V(),impactPoint=new V();
function fire(){if(!player.alive||player.reload>0||player.fireCooldown>0)return;const w=weaponStats();if(player.ammo[player.slot]<=0){reload();return;}player.ammo[player.slot]--;player.fireCooldown=w.rate;player.shots++;weaponKick=.11;shake=.015;if(gun?.userData.muzzle){gun.userData.flashLife=.045;gun.userData.muzzle.visible=true;gun.userData.muzzle.rotation.z=Math.random()*6.28;}AudioManager.play(w.type==='sniper'?'sniper':'shot',0,w);const ads=input.ads?(w.type==='sniper'?.02:w.type==='shotgun'?.8:.08):1;getEye(bulletOrigin);
for(let pellet=0;pellet<(w.pellets||1);pellet++){const py=pitch+(Math.random()-.5)*w.spread*ads,yy=yaw+(Math.random()-.5)*w.spread*ads;bulletDirection.set(-Math.sin(yy)*Math.cos(py),Math.sin(py),-Math.cos(yy)*Math.cos(py));let dist=wallDistance(bulletOrigin,bulletDirection,w.range),target=null,head=false;
for(const b of bots){if(!b.alive||match.teamMode&&b.team===player.team)continue;const c={x1:b.pos.x-.30,x2:b.pos.x+.30,z1:b.pos.z-.27,z2:b.pos.z+.27,y1:b.pos.y,y2:b.pos.y+1.78};const d=rayBox(bulletOrigin,bulletDirection,c,dist);if(d<dist){dist=d;target=b;head=bulletOrigin.y+bulletDirection.y*d>b.pos.y+1.44;}}
impactPoint.copy(bulletOrigin).addScaledVector(bulletDirection,dist);tracer(bulletOrigin,impactPoint);burst(impactPoint,3,target?0xb76454:0xc6b38a,2);if(target){const damage=w.damage*(head?2.5:1)*lerp(1,.5,clamp(dist/w.range,0,1));damageBot(target,damage,head,dist,true);player.hits++;hitTime=.16;AudioManager.play('hit');}else if(dist<w.range)AudioManager.play('click',dist);}
pitch=clamp(pitch+w.recoil*(input.ads?.6:1),-1.45,1.45);yaw+=(Math.random()-.5)*w.recoil*.5;for(const b of bots)if(b.alive&&b.pos.distanceTo(player.pos)<32){b.memory.copy(player.pos);b.memoryTime=4;}}
function melee(){if(player.fireCooldown>0||!player.alive)return;player.fireCooldown=.65;weaponKick=.35;AudioManager.play('click');const origin=player.pos.clone().add(new V(0,1,0)),forward=new V(-Math.sin(yaw),0,-Math.cos(yaw));let best=null,distance=2.3;for(const b of bots){if(!b.alive||match.teamMode&&b.team===player.team)continue;const d=b.pos.clone().sub(player.pos),dist=d.length();if(dist<distance&&d.normalize().dot(forward)>.65&&visible(origin,b.pos.clone().add(new V(0,1,0)))){best=b;distance=dist;}}if(best){damageBot(best,80,false,distance,true);hitTime=.2;}}
function safeSpawn(team,avoid=true){let best=world.spawns[0],value=-Infinity;for(const s of world.spawns){if(match?.teamMode&&Math.sign(s.z)!==(team===0?1:-1))continue;let nearest=100;for(const b of bots)if(b.alive&&(!match.teamMode||b.team!==team))nearest=Math.min(nearest,b.pos.distanceTo(s));if(avoid&&player.alive&&team!==0)nearest=Math.min(nearest,player.pos.distanceTo(s));const score=nearest+Math.random()*4;if(score>value&&!blocked(s.x,s.z,s.y)){best=s;value=score;}}return best.clone();}
function spawnPlayer(){leanAmount=0;input.lean=0;player.pos.copy(safeSpawn(0));player.prev.copy(player.pos);player.vel.set(0,0,0);player.health=100;player.armor=50;player.alive=true;player.invulnerable=2;player.grenades=3;player.slide=0;player.slot=0;player.eye=1.65;setGun(true);player.ammo[1]=WEAPONS[save.loadout.secondary].mag;yaw=0;pitch=0;deathTimer=0;}
function damagePlayer(amount,from,killer=null){if(!player.alive||player.invulnerable>0)return;const absorb=Math.min(player.armor,amount*.35);player.armor-=absorb;player.health-=amount-absorb;hurtTime=.35;shake=.06;if(player.health<=0){player.health=0;player.alive=false;player.deaths++;if(killer){killer.kills++;if(match.mode==='Gun Game')upgradeBotGun(killer);}deathTimer=3;input.fire=false;if(match.mode==='Survival'){endMatch(false);return;}if(match.teamMode)match.scores[1]++;feed('You were eliminated');}AudioManager.play('hit');}
function damageBot(b,amount,head,dist,byPlayer){if(!b.alive)return;b.health-=amount;if(byPlayer){player.damage+=Math.min(amount,b.health+amount);b.memory.copy(player.pos);b.memoryTime=5;}if(b.health>0)return;b.alive=false;b.respawn=3;b.mesh.rotation.z=.9;b.mesh.position.y-=.4;b.deaths++;if(byPlayer){player.kills++;if(head)player.headshots++;player.longest=Math.max(player.longest,dist);feed((head?'HEADSHOT · ':'')+b.name);save.mastery[getWeaponId()]=(save.mastery[getWeaponId()]||0)+1;if(match.teamMode)match.scores[0]++;if(match.mode==='Gun Game'){player.tier++;setGun(true);if(player.tier>=8)endMatch(true);}}if(match.mode==='Training Range'){b.respawn=.8;}AudioManager.play('hit');checkWin();}
function feed(message){const p=document.createElement('div');p.textContent=message;$('#feed').prepend(p);while($('#feed').children.length>4)$('#feed').lastChild.remove();}
function createBots(count){for(let i=0;i<count;i++){const team=match.mode==='Survival'?1:match.teamMode?(i%2===0?1:0):1,mesh=makeCharacter(team);const weaponId=match.mode==='Sniper Only'?3:match.mode==='Gun Game'?0:[0,2,3,5][i%4];mesh.remove(mesh.userData.gun);const botGun=makeGun(weaponId,true);botGun.position.set(.1,.99,-.36);mesh.add(botGun);mesh.userData.gun=botGun;scene.add(mesh);const b={name:['Viper','Hawk','Rook','Sable','Ghost','Mako','Reign','Atlas'][i%8]+' '+(i+1),pos:safeSpawn(team),vel:new V(),team,mesh,weaponId,health:100,alive:true,grounded:true,respawn:0,kills:0,deaths:0,state:'Patrol',path:[],pathIndex:0,decision:i*.08,fire:.5+Math.random(),ammo:30,reload:0,memory:new V(),memoryTime:0,blind:0,personality:i%4,target:null,stuck:0,lastPos:new V(),seen:false,phase:Math.random()*7};b.mesh.position.copy(b.pos);bots.push(b);}}
function upgradeBotGun(b){b.weaponId=[0,2,1,4,5,6,7,3][Math.min(b.kills,7)];b.mesh.remove(b.mesh.userData.gun);const g=makeGun(b.weaponId,true);g.position.set(.1,.99,-.36);b.mesh.add(g);b.mesh.userData.gun=g;b.ammo=WEAPONS[b.weaponId].mag;}
function botTarget(b){let target=null,dist=Infinity;const eye=b.pos.clone().add(new V(0,1.5,0));for(const e of [player,...bots]){if(e===b||!e.alive||match.teamMode&&e.team===b.team||match.mode==='Survival'&&e!==player)continue;const d=b.pos.distanceTo(e.pos);if(d>Math.min(dist,save.config.weather==='Dense fog'?18:55))continue;const angle=Math.atan2(-(e.pos.x-b.pos.x),-(e.pos.z-b.pos.z));const diff=Math.atan2(Math.sin(angle-b.mesh.rotation.y),Math.cos(angle-b.mesh.rotation.y));if(Math.abs(diff)>1.8&&d>10&&b.memoryTime<=0)continue;if(visible(eye,e===player?getEye(new V()):e.pos.clone().add(new V(0,1.25,0)))){target=e;dist=d;}}return target;}
function decideBot(b){if(match.mode==='Training Range'){b.state='Target';return;}b.target=b.blind>0?null:botTarget(b);if(b.target){b.memory.copy(b.target.pos);b.memoryTime=4;b.state=b.health<35?'Retreat':'Engage';if(b.health<35){let best=null,bestScore=-Infinity;for(const cover of world.cover){const score=cover.distanceTo(b.target.pos)-cover.distanceTo(b.pos)*.6;if(score>bestScore){bestScore=score;best=cover;}}if(best){b.path=pathTo(b.pos,best);b.pathIndex=0;}}else if(b.pos.distanceTo(b.target.pos)>18||b.personality===2){const flank=b.target.pos.clone();flank.x+=b.personality===2?8:0;b.path=pathTo(b.pos,flank);b.pathIndex=0;}}
else{b.state=b.memoryTime>0?'Search':'Patrol';if(b.pathIndex>=b.path.length){const dest=b.memoryTime>0?b.memory:world.spawns[Math.floor(Math.random()*world.spawns.length)];b.path=pathTo(b.pos,dest);b.pathIndex=0;}}
for(const g of grenades)if(b.pos.distanceTo(g.pos)<7){const dest=b.pos.clone().sub(g.pos).normalize().multiplyScalar(10).add(b.pos);b.path=pathTo(b.pos,dest);b.pathIndex=0;b.state='Evade';}}
function updateBots(dt){const difficulty=['Recruit','Regular','Veteran','Elite'].indexOf(save.config.difficulty);for(const b of bots){if(!b.alive){b.respawn-=dt;if(b.respawn<=0&&match.mode!=='Survival'){b.pos.copy(safeSpawn(b.team));b.vel.set(0,0,0);b.alive=true;b.health=100;b.ammo=30;b.mesh.rotation.z=0;b.path=[];b.pathIndex=0;}continue;}b.blind=Math.max(0,b.blind-dt);b.memoryTime-=dt;b.decision-=dt;b.fire-=dt;b.reload-=dt;
if(b.decision<=0){decideBot(b);b.decision=.3+(b.pos.distanceTo(player.pos)>35?.3:0);}
let dx=0,dz=0;if(match.mode==='Training Range'){if(b.personality%2){dx=Math.cos(clock*.9+b.phase)*2;dz=Math.sin(clock*.9+b.phase)*.5;}}
else if(b.pathIndex<b.path.length){const point=b.path[b.pathIndex],dist=Math.hypot(point.x-b.pos.x,point.z-b.pos.z);if(dist<.9)b.pathIndex++;else{dx=(point.x-b.pos.x)/dist*3.2;dz=(point.z-b.pos.z)/dist*3.2;}}
else if(b.target&&b.state==='Engage'){const d=b.target.pos.clone().sub(b.pos),dist=d.length(),strafe=Math.sin(clock*1.6+b.phase)*1.7;dx=d.x/(dist||1)*(dist>14?2:dist<7?-1:0)+d.z/(dist||1)*strafe;dz=d.z/(dist||1)*(dist>14?2:dist<7?-1:0)-d.x/(dist||1)*strafe;}
b.vel.x=lerp(b.vel.x,dx,dt*6);b.vel.z=lerp(b.vel.z,dz,dt*6);moveBody(b,dt);const moved=b.pos.distanceToSquared(b.lastPos);b.stuck=moved<.0001&&Math.abs(dx)+Math.abs(dz)>1?b.stuck+dt:0;b.lastPos.copy(b.pos);if(b.stuck>1.2){b.path=[];b.pathIndex=0;b.decision=0;b.stuck=0;b.vel.x=-dx;b.vel.z=-dz;}
if(b.target){const angle=Math.atan2(-(b.target.pos.x-b.pos.x),-(b.target.pos.z-b.pos.z));b.mesh.rotation.y+=Math.atan2(Math.sin(angle-b.mesh.rotation.y),Math.cos(angle-b.mesh.rotation.y))*Math.min(1,dt*6);const distance=b.pos.distanceTo(b.target.pos);if(b.fire<=0&&b.blind<=0&&b.reload<=0&&b.target.alive&&visible(b.pos.clone().add(new V(0,1.4,0)),b.target===player?getEye(new V()):b.target.pos.clone().add(new V(0,1.3,0)))){const weapon=WEAPONS[b.weaponId];b.fire=weapon.rate+(3-difficulty)*.10+Math.random()*.18;if(b.ammo<=0){b.reload=weapon.reload;b.ammo=weapon.mag;b.state='Reload';}else{b.ammo--;const accuracy=clamp(.54+difficulty*.09-distance*.006-Math.hypot(b.vel.x,b.vel.z)*.03,.1,.85);if(Math.random()<accuracy){if(b.target===player)damagePlayer(weapon.damage*.58,b.pos,b);else{const e=b.target;e.health-=weapon.damage*.65;if(e.health<=0){e.alive=false;e.respawn=3;e.deaths++;b.kills++;if(match.mode==='Gun Game')upgradeBotGun(b);if(match.teamMode)match.scores[b.team]++;e.mesh.rotation.z=.9;feed(b.name+' → '+e.name);}}}const a=b.pos.clone().add(new V(0,1.25,0)),end=b.target.pos.clone().add(new V((Math.random()-.5)*1.5,1.2,0));tracer(a,end);AudioManager.play('shot',distance,weapon);}}}
else if(Math.abs(dx)+Math.abs(dz)>.3){const angle=Math.atan2(-dx,-dz);b.mesh.rotation.y+=Math.atan2(Math.sin(angle-b.mesh.rotation.y),Math.cos(angle-b.mesh.rotation.y))*Math.min(1,dt*5);}
b.mesh.position.copy(b.pos);const speed=Math.hypot(b.vel.x,b.vel.z),cycle=clock*8+b.phase;b.mesh.userData.legs[0].rotation.x=Math.sin(cycle)*.55*speed/4;b.mesh.userData.legs[1].rotation.x=-Math.sin(cycle)*.55*speed/4;b.mesh.userData.arms[0].rotation.x=-.3+Math.sin(cycle)*.1;b.mesh.userData.arms[1].rotation.x=-.6;b.mesh.visible=b.pos.distanceToSquared(player.pos)<10000;}
checkWin();}
function updatePlayer(dt){player.prev.copy(player.pos);player.invulnerable-=dt;player.fireCooldown=Math.max(0,player.fireCooldown-dt);if(!player.alive){deathTimer-=dt;if(deathTimer<=0&&appState==='game')spawnPlayer();return;}if(player.reload>0){player.reload-=dt;if(player.reload<=0){player.ammo[player.slot]=weaponStats().mag;AudioManager.play('click');}}
let ix=input.x+(keys.KeyD?1:0)-(keys.KeyA?1:0),iz=input.z+(keys.KeyS?1:0)-(keys.KeyW?1:0),len=Math.hypot(ix,iz);if(len>1){ix/=len;iz/=len;}const crouched=input.crouch||keys.ControlLeft, sprint=input.sprint||keys.ShiftLeft||save.settings.autoSprint;player.slide=Math.max(0,player.slide-dt);const height=crouched||player.slide>0?1:1.7;player.eye=lerp(player.eye,height-.06,dt*12);const speed=(crouched?2.5:sprint?7.6:5.3)*(WEAPONS[getWeaponId()].type==='lmg'?.85:1);let wishX=ix*Math.cos(yaw)+iz*Math.sin(yaw),wishZ=-ix*Math.sin(yaw)+iz*Math.cos(yaw);const wishLen=Math.hypot(wishX,wishZ);if(wishLen>0){wishX/=wishLen;wishZ/=wishLen;}
const wantsJump=input.jump||keys.Space;if(wantsJump)player.jumpBuffer=.12;else player.jumpBuffer=Math.max(0,player.jumpBuffer-dt);if(player.grounded)player.coyote=.09;else player.coyote-=dt;
const hop=player.jumpBuffer>0&&player.coyote>0;if(player.grounded&&!hop&&player.slide<=0){const horizontal=Math.hypot(player.vel.x,player.vel.z),drop=Math.max(horizontal,2)*8*dt,ratio=Math.max(0,horizontal-drop)/(horizontal||1);player.vel.x*=ratio;player.vel.z*=ratio;}
if(wishLen>0&&player.slide<=0){const target=player.grounded?speed:2.3,current=player.vel.x*wishX+player.vel.z*wishZ,add=Math.max(0,target-current),accel=Math.min(add,(player.grounded?55:14)*dt*speed/5);player.vel.x+=wishX*accel;player.vel.z+=wishZ*accel;}
if(player.slide>0){const friction=Math.exp(-.8*dt);player.vel.x*=friction;player.vel.z*=friction;}
const horizontal=Math.hypot(player.vel.x,player.vel.z);if(horizontal>13){player.vel.x*=13/horizontal;player.vel.z*=13/horizontal;}
if(hop){player.vel.y=8;player.grounded=false;player.coyote=0;player.jumpBuffer=0;if(!save.settings.autoHop){input.jump=false;keys.Space=false;}AudioManager.play('step');}
moveBody(player,dt,height);updateLean(dt);if(input.fire||keys.Mouse0)fire();}
function slide(){if(player.grounded&&Math.hypot(player.vel.x,player.vel.z)>4){player.slide=.9;player.vel.x*=1.15;player.vel.z*=1.15;}else input.crouch=!input.crouch;}
function checkWin(){if(!match||appState!=='game')return;if(match.mode==='Survival'){if(bots.every(b=>!b.alive)){match.wave++;if(match.wave>5){endMatch(true);return;}for(const b of bots){scene.remove(b.mesh);}bots=[];createBots(Math.min(5+match.wave*2,18));player.health=Math.min(100,player.health+25);player.grenades=Math.min(3,player.grenades+1);feed('WAVE '+match.wave+' · incoming');}return;}
if(match.mode==='Training Range')return;if(match.mode==='Gun Game'&&bots.some(b=>b.kills>=8)){endMatch(false);return;}if(match.teamMode){if(match.scores[0]>=match.limit||match.scores[1]>=match.limit)endMatch(match.scores[0]>match.scores[1]);}else if(match.mode!=='Gun Game'){let leader=player.kills;for(const b of bots)leader=Math.max(leader,b.kills);if(leader>=match.limit)endMatch(player.kills>=match.limit);}}
function startMatch(){window.FZApp?.enterFullscreen();AudioManager.init();readConfig();$('#menu').hidden=true;$('#panel').hidden=true;$('#results').hidden=true;$('#loading').hidden=false;appState='loading';setTimeout(()=>{try{buildWorld(MAPS.indexOf(save.config.map),Number(save.config.seed));scene.remove(preview);match={mode:save.config.mode,teamMode:['Team Deathmatch','Custom Match','Sniper Only'].includes(save.config.mode),scores:[0,0],limit:Number(save.config.limit),remaining:Number(save.config.duration),duration:Number(save.config.duration),wave:1};Object.assign(player,{kills:0,deaths:0,headshots:0,damage:0,shots:0,hits:0,longest:0,tier:0,alive:true});appState='game';spawnPlayer();createBots(match.mode==='Training Range'?8:match.mode==='Survival'?7:Number(save.config.bots));$('#loading').hidden=true;$('#hud').hidden=false;$('#pause').hidden=true;$('#feed').textContent='';applyLayout();toast(match.mode==='Training Range'?'Test weapons on static and moving targets. End from Pause.':'Stay mobile. Control the lanes.');}catch(e){fatal(e);$('#loading').hidden=true;}},70);}
function endMatch(won){if(appState!=='game')return;appState='results';input.fire=false;input.ads=false;$('#hud').hidden=true;$('#pause').hidden=true;document.exitPointerLock?.();const earned=Math.round(player.kills*55+player.damage*.06+(won?200:80));save.xp+=earned;save.stats.kills+=player.kills;save.stats.deaths+=player.deaths;save.stats.matches++;save.stats.wins+=won?1:0;save.stats.shots+=player.shots;save.stats.hits+=player.hits;save.history.push({mode:match.mode,map:save.config.map,kills:player.kills,deaths:player.deaths,won,xp:earned,date:Date.now()});save.history=save.history.slice(-20);persist();$('#results').hidden=false;$('#resultTitle').textContent=match.mode==='Training Range'?'RANGE REPORT':won?'VICTORY':'DEFEAT';$('#resultDetails').innerHTML=`<div><strong>${player.kills}</strong>ELIMINATIONS</div><div><strong>${player.deaths}</strong>DEATHS</div><div><strong>${Math.round(player.hits/Math.max(1,player.shots)*100)}%</strong>HIT RATE*</div><div><strong>${player.headshots}</strong>HEADSHOTS</div><div><strong>${Math.round(player.damage)}</strong>DAMAGE</div><div><strong>${Math.round(player.longest)}m</strong>LONGEST KILL</div>`;$('#resultXP').textContent=`+${earned} XP · LEVEL ${1+Math.floor(save.xp/1000)} · ${Math.round(match.duration-match.remaining)} seconds`;}
function goMenu(){appState='menu';$('#hud').hidden=true;$('#pause').hidden=true;$('#results').hidden=true;$('#panel').hidden=true;$('#menu').hidden=false;weaponRoot.visible=false;document.exitPointerLock?.();input.fire=input.ads=false;clearEffects();buildWorld(MAPS.indexOf(save.config.map),Number(save.config.seed));updateProfile();}
function clearEffects(){for(const g of grenades)g.mesh.visible=false;grenades.length=0;for(const s of smokes){scene.remove(s.group);s.material.dispose();}smokes.length=0;for(const p of particlePool){p.life=0;p.mesh.visible=false;}for(const t of tracers){t.life=0;t.mesh.visible=false;}}
function updateProfile(){$('#profile').textContent=`OPERATOR / LEVEL ${1+Math.floor(save.xp/1000)} · ${save.xp%1000}/1000 XP`;}
function selectOptions(arr,value){return arr.map((v,i)=>`<option value="${typeof v==='string'?v:i}" ${value===(typeof v==='string'?v:i)?'selected':''}>${typeof v==='string'?v:v.name}</option>`).join('');}
function configHTML(){const c=save.config;return `<div class="formgrid"><label>Operation<select id="cfgMode">${selectOptions(MODES,c.mode)}</select></label><label>Arena<select id="cfgMap">${selectOptions(MAPS,c.map)}</select></label><label>Difficulty<select id="cfgDifficulty">${selectOptions(['Recruit','Regular','Veteran','Elite'],c.difficulty)}</select></label><label>Opponents / allies<select id="cfgBots">${selectOptions([2,4,6,8,10,12].map(String),String(c.bots))}</select></label><label>Score limit<input id="cfgLimit" type="number" min="5" max="100" value="${c.limit}"></label><label>Seconds<input id="cfgDuration" type="number" min="30" max="900" value="${c.duration}"></label><label>Weather<select id="cfgWeather">${selectOptions(['Clear','Cloudy','Rain','Dense fog','Snow','Sandstorm'],c.weather)}</select></label><label>Lighting<select id="cfgTime">${selectOptions(['Midday','Sunset','Night','Dynamic'],c.time)}</select></label><label>Map seed<input id="cfgSeed" type="number" value="${c.seed}"></label></div><p class="muted">Two teams in TDM, Sniper Only and Custom. Survival: clear five waves. Gun Game: earn eight weapon-tier eliminations. The range ends when you select End match.</p>`;}
function readConfig(){if($('#cfgMode')){const fields={mode:'Mode',map:'Map',difficulty:'Difficulty',bots:'Bots',limit:'Limit',duration:'Duration',weather:'Weather',time:'Time',seed:'Seed'};for(const [key,id] of Object.entries(fields))save.config[key]=$('#cfg'+id).value;save.config.bots=clamp(+save.config.bots,2,12);save.config.limit=clamp(+save.config.limit||20,5,100);save.config.duration=clamp(+save.config.duration||180,30,900);save.config.seed=+save.config.seed||2026;}persist();}
function panel(title,html){$('#menu').hidden=true;$('#panel').hidden=false;$('#panelTitle').textContent=title;$('#panelBody').innerHTML=html;$('#panel').scrollTop=0;}
function lobby(){panel('DEPLOYMENT',`<p class="eyebrow">OFFLINE OPERATIONS / PROCEDURAL ARENAS</p>${configHTML()}<button class="primary" id="deploy">DEPLOY NOW <span>→</span></button><p class="muted">Desktop: WASD · Mouse aim · Space jump · Shift sprint · Ctrl crouch · C slide · R reload · X / 2 swap · RMB / Z ADS · Q / E peek · G grenade · V melee · Esc pause. Touch: left stick + right-side drag; action buttons support multiple pointers.</p>`);$('#deploy').onclick=startMatch;}
function loadout(){panel('ARMORY',`<div class="formgrid"><label>Primary<select id="primary">${selectOptions(WEAPONS,save.loadout.primary)}</select></label><label>Secondary<select id="secondary">${selectOptions(WEAPONS.filter(w=>w.type==='pistol').map(w=>w.name),WEAPONS[save.loadout.secondary].name)}</select></label><label>Attachment<select id="attachment">${selectOptions(['Red dot','4x scope','Suppressor','Compensator','Extended mag','Vertical grip'],save.loadout.attachment)}</select></label></div><p class="muted">Compensator: 30% less recoil. Grip: 20% less spread. Extended magazine: 30% more rounds. The 4x optic magnifies ADS. Suppressor changes the weapon mesh; sound suppression is not yet simulated.</p><div id="weaponCards" class="cards"></div><p class="muted">Release 1 includes these eight firearms and a combat knife. All are unlocked for testing. Mastery tracks eliminations offline.</p>`);function apply(){save.loadout.primary=+$('#primary').value;save.loadout.secondary=WEAPONS.findIndex(w=>w.name===$('#secondary').value);save.loadout.attachment=$('#attachment').value;persist();cards();}function cards(){$('#weaponCards').innerHTML=WEAPONS.map((w,i)=>`<div class="card ${save.loadout.primary===i?'selected':''}"><small>${w.type.toUpperCase()}</small><h3>${w.name}</h3><p>${w.mag} ROUNDS · ${Math.round(60/w.rate)} RPM</p><p>MASTERY ${save.mastery[i]||0}</p></div>`).join('');}$('#primary').onchange=$('#secondary').onchange=$('#attachment').onchange=apply;cards();}
function settings(){const s=save.settings;panel('SYSTEMS',`<div class="formgrid"><label>Input mode<select data-setting="inputMode">${selectOptions(['Auto','Keyboard / mouse','Touch'],s.inputMode)}</select></label><label>Graphics<select data-setting="quality">${selectOptions(['Ultra Low','Low','Balanced','High','Ultra','Automatic'],s.quality)}</select></label><label>Resolution <input data-setting="scale" type="range" min=".4" max="1" step=".05" value="${s.scale}"></label><label>Field of view<input data-setting="fov" type="range" min="65" max="105" value="${s.fov}"></label><label>Look sensitivity<input data-setting="sensitivity" type="range" min=".2" max="3" step=".1" value="${s.sensitivity}"></label><label>ADS sensitivity<input data-setting="adsSensitivity" type="range" min=".1" max="1.5" step=".05" value="${s.adsSensitivity}"></label><label>Master volume<input data-setting="volume" type="range" min="0" max="1" step=".05" value="${s.volume}"></label>${['autoHop','autoSprint','assist','shake','invert','fps','bloom'].map(k=>`<label class="check"><input data-setting="${k}" type="checkbox" ${s[k]?'checked':''}>${{autoHop:'Automatic bunny hop',autoSprint:'Automatic sprint',assist:'Touch aim slowdown',shake:'Camera shake',invert:'Invert vertical look',fps:'Performance diagnostics',bloom:'Atmospheric bloom'}[k]}</label>`).join('')}</div><div class="buttonrow"><button id="editHUD">EDIT TOUCH HUD</button><button id="exportSave">EXPORT SAVE</button><label class="button">IMPORT SAVE<input type="file" id="importSave" accept="application/json" hidden></label><button id="resetSave">RESET PROGRESS</button></div><p class="muted">Graphics presets affect render resolution, shadows, particle budget and view distance. Automatic adjusts resolution based on frame time. File-browser storage support varies; export your save before moving or renaming this file.</p>`);
for(const e of document.querySelectorAll('[data-setting]'))e.onchange=()=>{save.settings[e.dataset.setting]=e.type==='checkbox'?e.checked:e.tagName==='SELECT'?e.value:+e.value;renderScale=save.settings.scale;applyQuality();detectInput();persist();};$('#editHUD').onclick=()=>{$('#panel').hidden=true;if(appState==='menu'){match={mode:'Training Range',teamMode:false};appState='editor';$('#panel').hidden=true;$('#hud').hidden=false;}editing=true;$('#editor').hidden=false;$('#hud').classList.add('editing');applyLayout();};$('#exportSave').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(save,null,2)],{type:'application/json'}));a.download='frontline-zero-save.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);};$('#importSave').onchange=async e=>{try{const data=JSON.parse(await e.target.files[0].text());if(data.version!==1||!data.settings||!data.stats||!data.loadout)throw Error('Unsupported save');const restored=structuredClone(defaults);for(const k of ['xp','stats','mastery','history','loadout','settings','layout','config'])if(data[k]!=null)restored[k]=data[k];restored.settings={...defaults.settings,...restored.settings};restored.config={...defaults.config,...restored.config};restored.loadout.primary=clamp(+restored.loadout.primary||0,0,7);restored.loadout.secondary=clamp(+restored.loadout.secondary||6,6,7);restored.xp=Math.max(0,+restored.xp||0);save=restored;validateSave();persist();toast('Save imported');settings();}catch(e){toast('Import rejected: '+e.message);}};$('#resetSave').onclick=()=>{if(confirm('Reset progression, settings and loadout?')){save=structuredClone(defaults);persist();settings();toast('Save reset');}};}
function profile(){panel('OPERATOR RECORD',`<p class="eyebrow">LEVEL ${1+Math.floor(save.xp/1000)} / ${save.xp} XP</p><div class="cards">${Object.entries(save.stats).map(([k,v])=>`<div class="card"><h3>${v}</h3><small>${k.toUpperCase()}</small></div>`).join('')}</div><h3>RECENT OPERATIONS</h3>${save.history.slice().reverse().map(h=>`<p>${h.won?'VICTORY':'DEFEAT'} · ${h.map} · ${h.mode} · ${h.kills}/${h.deaths} · +${h.xp} XP</p>`).join('')||'<p class="muted">Your first operation starts here.</p>'}`);}
function pause(){if(appState==='game'){appState='paused';$('#pause').hidden=false;input.fire=false;input.ads=false;input.lean=0;keys.Mouse0=false;keys.KeyE=keys.KeyQ=false;input.jump=false;document.exitPointerLock?.();}else if(appState==='paused'){appState='game';$('#pause').hidden=true;$('#panel').hidden=true;if(desktop){const lock=renderer.domElement.requestPointerLock?.();lock?.catch?.(()=>toast('Click the scene to capture your mouse.'));}}}
let desktop=false,leanAmount=0;const eyeBase=new V(),eyeOffset=new V();
function detectInput(pointer){const mode=save.settings.inputMode;desktop=mode==='Keyboard / mouse'||mode!=='Touch'&&(pointer?pointer==='mouse':typeof matchMedia==='function'&&matchMedia('(hover: hover) and (pointer: fine)').matches);document.body?.classList.toggle('desktop',desktop);$('#pcHints').hidden=!desktop;$('#portrait').hidden=desktop||innerWidth>=innerHeight;return desktop;}
function updateLean(dt){const target=clamp(input.lean+(keys.KeyE?1:0)-(keys.KeyQ?1:0),-1,1);const requested=lerp(leanAmount,target,Math.min(1,dt*14));eyeBase.copy(player.pos);eyeBase.y+=player.eye;eyeOffset.set(Math.cos(yaw)*requested*.42,0,-Math.sin(yaw)*requested*.42);const length=eyeOffset.length();if(length>0){rayDir.copy(eyeOffset).normalize();const allowed=Math.max(0,wallDistance(eyeBase,rayDir,length+.10)-.10);leanAmount=requested*Math.min(1,allowed/length);}else leanAmount=0;}
function getEye(out){out.copy(player.pos);out.x+=Math.cos(yaw)*leanAmount*.42;out.y+=player.eye;out.z-=Math.sin(yaw)*leanAmount*.42;return out;}
const touchPointers=new Map();let joystickPointer=null,lookPointer=null,lookLast={x:0,y:0},editorSelection=null;const stick=$('#joystick'),knob=$('#knob');
function applyLayout(){for(const el of document.querySelectorAll('.control')){const p=save.layout[el.id];el.style.left=p?p.x+'%':'';el.style.top=p?p.y+'%':'';el.style.right=p?'auto':'';el.style.bottom=p?'auto':'';el.style.transform=p?'translate(-50%,-50%)':'';el.style.width=p?p.size+'px':'';el.style.height=p?p.size+'px':'';el.style.opacity=p?p.opacity:'';}}
function look(dx,dy){let sensitivity=.003*save.settings.sensitivity*(input.ads?save.settings.adsSensitivity:1);if(save.settings.assist&&match&&'ontouchstart'in window){for(const b of bots)if(b.alive&&(!match.teamMode||b.team!==0)){const angle=Math.atan2(-(b.pos.x-player.pos.x),-(b.pos.z-player.pos.z)),diff=Math.atan2(Math.sin(angle-yaw),Math.cos(angle-yaw));if(Math.abs(diff)<.04&&b.pos.distanceTo(player.pos)<35&&visible(player.pos.clone().add(new V(0,1.4,0)),b.pos.clone().add(new V(0,1.3,0)))){sensitivity*=.65;break;}}}yaw-=dx*sensitivity;pitch=clamp(pitch-dy*sensitivity*(save.settings.invert?-1:1),-1.45,1.45);}
function stickMove(e){const r=stick.getBoundingClientRect(),dx=e.clientX-r.left-r.width/2,dy=e.clientY-r.top-r.height/2,radius=r.width*.36,length=Math.hypot(dx,dy),ratio=Math.min(1,radius/(length||1));knob.style.transform=`translate(${dx*ratio}px,${dy*ratio}px)`;input.x=clamp(dx/radius,-1,1);input.z=clamp(dy/radius,-1,1);}
function releasePointer(id){const data=touchPointers.get(id);if(!data)return;if(data.action==='fire')input.fire=[...touchPointers.entries()].some(([pointer,value])=>pointer!==id&&value.action==='fire');if(data.action==='leanLeft'||data.action==='leanRight')input.lean=[...touchPointers.entries()].reduce((sum,[pointer,value])=>pointer===id?sum:sum+(value.action==='leanLeft'?-1:value.action==='leanRight'?1:0),0);if(data.action==='jump')input.jump=false;if(data.action==='sprint')input.sprint=false;if(id===joystickPointer){joystickPointer=null;input.x=input.z=0;knob.style.transform='';}if(id===lookPointer)lookPointer=null;touchPointers.delete(id);}
const actions={leanLeft:()=>{input.lean=-1;},leanRight:()=>{input.lean=1;},fire:()=>{input.fire=true;},ads:()=>{input.ads=!input.ads;},jump:()=>{input.jump=true;},crouch:()=>{input.crouch=!input.crouch;},sprint:()=>{input.sprint=true;},slide,reload,swap:switchWeapon,grenade:throwGrenade,melee,pause,interact:()=>{if(player.pos.distanceTo(new V(0,0,32))<7){player.ammo[player.slot]=weaponStats().mag;player.grenades=3;toast('Supply replenished');}else toast('Supply cache is near the south spawn.');},throwtype:()=>{const types=['Frag','Smoke','Flash'];player.throwType=types[(types.indexOf(player.throwType)+1)%3];toast(player.throwType+' selected');}};
$('#hud').addEventListener('pointerdown',e=>{if(appState!=='game'&&!editing)return;if(e.pointerType==='touch')detectInput('touch');AudioManager.init();const control=e.target.closest('.control');if(editing){if(!control)return;editorSelection=control;const r=control.getBoundingClientRect();$('#buttonSize').value=r.width;$('#buttonOpacity').value=control.style.opacity||.65;touchPointers.set(e.pointerId,{el:control,edit:true});control.setPointerCapture(e.pointerId);e.preventDefault();return;}
if(control){control.setPointerCapture(e.pointerId);const action=control.dataset.action;touchPointers.set(e.pointerId,{action,el:control});if(control===stick){if(joystickPointer!==null)return;joystickPointer=e.pointerId;stickMove(e);}else if(actions[action])actions[action]();e.preventDefault();}
else if(e.clientX>innerWidth*.35&&lookPointer===null){lookPointer=e.pointerId;lookLast={x:e.clientX,y:e.clientY};touchPointers.set(e.pointerId,{action:'look'});$('#hud').setPointerCapture(e.pointerId);e.preventDefault();}});
window.addEventListener('pointermove',e=>{const data=touchPointers.get(e.pointerId);if(data?.edit){const el=data.el,old=save.layout[el.id]||{size:el.getBoundingClientRect().width,opacity:.65};save.layout[el.id]={...old,x:clamp(e.clientX/innerWidth*100,3,97),y:clamp(e.clientY/innerHeight*100,5,95)};applyLayout();return;}if(e.pointerId===joystickPointer)stickMove(e);else if(e.pointerId===lookPointer){look(e.clientX-lookLast.x,e.clientY-lookLast.y);lookLast={x:e.clientX,y:e.clientY};}else if(document.pointerLockElement===renderer.domElement&&appState==='game')look(e.movementX,e.movementY);});
for(const event of ['pointerup','pointercancel','lostpointercapture'])window.addEventListener(event,e=>releasePointer(e.pointerId));
window.addEventListener('contextmenu',e=>e.preventDefault());window.addEventListener('keydown',e=>{if(e.target.matches('input,select'))return;detectInput('mouse');keys[e.code]=true;if(['Space','ArrowUp','ArrowDown','Tab'].includes(e.code))e.preventDefault();if(e.repeat)return;if(e.code==='Escape')pause();if(appState!=='game')return;if(e.code==='KeyR')reload();if(e.code==='Digit2'||e.code==='KeyX')switchWeapon();if(e.code==='KeyZ')input.ads=!input.ads;if(e.code==='KeyC')slide();if(e.code==='KeyG')throwGrenade();if(e.code==='KeyV')melee();if(e.code==='KeyF')actions.interact();if(e.code==='KeyT')actions.throwtype();});window.addEventListener('keyup',e=>{keys[e.code]=false;});
renderer.domElement.addEventListener('pointerdown',e=>{if(appState==='game'&&e.pointerType==='mouse'){detectInput('mouse');AudioManager.init();if(e.button===0){const lock=renderer.domElement.requestPointerLock?.();lock?.catch?.(()=>toast('Mouse capture unavailable. Try your normal browser.'));keys.Mouse0=true;}if(e.button===2)input.ads=true;}});window.addEventListener('pointerup',e=>{if(e.pointerType==='mouse'){if(e.button===0)keys.Mouse0=false;if(e.button===2)input.ads=false;}});window.addEventListener('blur',()=>{for(const key of Object.keys(keys))keys[key]=false;input.fire=false;input.ads=false;input.lean=0;if(appState==='game')pause();});document.addEventListener('pointerlockchange',()=>{if(!document.pointerLockElement&&desktop&&appState==='game')pause();});
$('#hud').addEventListener('dblclick',e=>e.preventDefault());
$('#buttonSize').oninput=e=>{if(!editorSelection)return;const el=editorSelection,r=el.getBoundingClientRect();save.layout[el.id]={...(save.layout[el.id]||{x:(r.left+r.width/2)/innerWidth*100,y:(r.top+r.height/2)/innerHeight*100,opacity:.65}),size:+e.target.value};applyLayout();};$('#buttonOpacity').oninput=e=>{if(!editorSelection)return;const el=editorSelection,r=el.getBoundingClientRect();save.layout[el.id]={...(save.layout[el.id]||{x:(r.left+r.width/2)/innerWidth*100,y:(r.top+r.height/2)/innerHeight*100,size:r.width}),opacity:+e.target.value};applyLayout();};
$('#preset').onchange=e=>{save.layout={};if(e.target.value==='Left handed'){save.layout.joystick={x:84,y:77,size:130,opacity:.65};save.layout.fire={x:14,y:50,size:78,opacity:.7};save.layout.fireLeft={x:80,y:26,size:64,opacity:.7};}if(e.target.value==='Three finger'||e.target.value==='Four finger'){save.layout.fireLeft={x:20,y:24,size:75,opacity:.7};save.layout.ads={x:86,y:20,size:58,opacity:.7};if(e.target.value==='Four finger')save.layout.jump={x:92,y:42,size:58,opacity:.7};}applyLayout();};$('#resetLayout').onclick=()=>{save.layout={};applyLayout();};$('#saveLayout').onclick=()=>{persist();editing=false;$('#editor').hidden=true;$('#hud').classList.remove('editing');if(appState==='editor'){appState='menu';$('#hud').hidden=true;settings();}if(appState==='paused')$('#pause').hidden=false;toast('Touch layout saved');};
let menuDrag=null;$('#menu').addEventListener('pointerdown',e=>{if(e.target.closest('button'))return;menuDrag=e.clientX;});window.addEventListener('pointermove',e=>{if(menuDrag!==null&&appState==='menu'){previewYaw+=(e.clientX-menuDrag)*.01;menuDrag=e.clientX;}});window.addEventListener('pointerup',()=>menuDrag=null);
function resize(){camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);$('#portrait').hidden=desktop||innerWidth>=innerHeight;applyLayout();}window.addEventListener('resize',resize);document.addEventListener('visibilitychange',()=>{if(document.hidden){for(const id of touchPointers.keys())releasePointer(id);for(const key of Object.keys(keys))keys[key]=false;if(appState==='game')pause();AudioManager.ctx?.suspend();}else AudioManager.ctx?.resume();lastTime=performance.now();accumulator=0;});renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();if(appState==='game')pause();toast('Graphics context lost. Waiting for recovery.');});renderer.domElement.addEventListener('webglcontextrestored',()=>{applyQuality();toast('Graphics recovered. Resume when ready.');});
function applyQuality(){const q=save.settings.quality,scales={'Ultra Low':.45,Low:.6,Balanced:.8,High:.95,Ultra:1};renderScale=q==='Automatic'?clamp(renderScale,.4,1):(scales[q]||.8)*save.settings.scale;renderer.setPixelRatio(Math.min(devicePixelRatio,q==='Ultra'?2:1.5)*renderScale);renderer.shadowMap.enabled=!['Ultra Low','Low'].includes(q);sun.castShadow=renderer.shadowMap.enabled;const size=['High','Ultra'].includes(q)?2048:1024;if(sun.shadow.mapSize.x!==size){sun.shadow.mapSize.set(size,size);sun.shadow.map?.dispose();sun.shadow.map=null;}if(scene.fog){scene.fog.far=q==='Ultra Low'?75:q==='Low'?100:155;}resize();}
const weatherCount=220,weatherPositions=new Float32Array(weatherCount*3);for(let i=0;i<weatherPositions.length;i++)weatherPositions[i]=(Math.random()-.5)*50;const weatherGeo=new THREE.BufferGeometry();weatherGeo.setAttribute('position',new THREE.BufferAttribute(weatherPositions,3));const weatherMat=new THREE.PointsMaterial({color:0xc6dcdf,size:.06,transparent:true,opacity:.45,depthWrite:false});const weatherPoints=new THREE.Points(weatherGeo,weatherMat);weatherPoints.frustumCulled=false;scene.add(weatherPoints);
const environmentColor=new THREE.Color();let weatherBlend=0;function environment(dt){const c=save.config,t=THEMES[world.theme],dynamic=c.time==='Dynamic',phase=dynamic?(clock*.008+.3)%1:c.time==='Night'?.78:c.time==='Midday'?.22:.43;const elevation=Math.sin(phase*Math.PI*2),day=clamp(elevation+.25,.10,1);sun.position.set(Math.cos(phase*Math.PI*2)*35,Math.max(4,elevation*40),20);sun.intensity=.35+day*3.7;sun.color.setHex(c.time==='Sunset'?0xffc38f:day<.3?0x89a6c4:0xffe8c4);hemi.intensity=.55+day*1.25;hemi.color.setHex(0xb9d8ef);hemi.groundColor.setHex(0x4e493b);const sky=environmentColor.setHex(t.sky).multiplyScalar(.14+day*.86);scene.background.copy(sky);scene.fog.color.copy(sky);updateSky(day,phase,t);const wet=['Rain','Snow','Sandstorm'].includes(c.weather);weatherBlend=lerp(weatherBlend,wet?1:0,Math.min(1,dt*.5));weatherPoints.visible=weatherBlend>.01;weatherGeo.setDrawRange(0,save.settings.quality==='Ultra Low'?70:save.settings.quality==='Low'?120:220);weatherPoints.position.set(appState==='game'?player.pos.x:0,12,appState==='game'?player.pos.z:0);weatherMat.opacity=weatherBlend*.5;weatherMat.size=c.weather==='Snow'?.12:c.weather==='Sandstorm'?.1:.055;weatherMat.color.setHex(c.weather==='Sandstorm'?0xc6b17d:0xc6dcdf);if(weatherPoints.visible){const a=weatherGeo.attributes.position;const speed=c.weather==='Rain'?18:c.weather==='Snow'?2:4;for(let i=0;i<weatherCount;i++){weatherPositions[i*3+1]-=dt*speed;weatherPositions[i*3]+=(c.weather==='Sandstorm'?6:1)*dt;if(weatherPositions[i*3+1]<-14)weatherPositions[i*3+1]=14;if(weatherPositions[i*3]>25)weatherPositions[i*3]=-25;}a.needsUpdate=true;}const fogTarget=c.weather==='Dense fog'?36:c.weather==='Sandstorm'?48:c.weather==='Rain'?85:save.settings.quality==='Ultra Low'?75:155;scene.fog.far=lerp(scene.fog.far,fogTarget,dt*.5);}
const mapCanvas=$('#minimap'),mapCtx=mapCanvas.getContext('2d');let hudTimer=0;
function hud(dt){hudTimer-=dt;if(hudTimer>0)return;hudTimer=.1;const w=weaponStats();$('#ammo').textContent=`${player.ammo[player.slot]} / ${w.mag}`;$('#weaponName').textContent=w.name;$('#healthFill').style.width=player.health+'%';$('#armorFill').style.width=player.armor*2+'%';$('#hp').textContent=Math.ceil(player.health);$('#timer').textContent=`${Math.floor(match.remaining/60)}:${String(Math.floor(match.remaining%60)).padStart(2,'0')}`;$('#score').textContent=match.mode==='Survival'?`WAVE ${match.wave}/5`:match.mode==='Gun Game'?`TIER ${Math.min(player.tier+1,8)}/8`:match.teamMode?`${match.scores[0]} : ${match.scores[1]}`:`${player.kills} ELIM / ${match.limit}`;$('#modeLabel').textContent=match.mode.toUpperCase();$('#compass').textContent=['N','NE','E','SE','S','SW','W','NW'][((Math.round(-yaw/(Math.PI/4))%8)+8)%8]+' · '+Math.round(((-yaw*180/Math.PI)%360+360)%360)+'°';$('#grenade').innerHTML=iconMarkup('grenade')+'<span class="grenade-count">'+player.grenades+'</span>'; $('#throwtype').textContent=player.throwType.toUpperCase();$('#reloadText').textContent=player.reload>0?'RELOADING '+player.reload.toFixed(1)+'s':player.slide>0?'SLIDING':player.invulnerable>0?'SPAWN PROTECTION':'';$('#dead').hidden=player.alive;$('#dead').textContent='ELIMINATED · RESPAWN '+Math.ceil(deathTimer);$('#diag').hidden=!save.settings.fps;$('#diag').textContent=`${Math.round(fps)} FPS · ${renderer.info.render.calls} draws · ${Math.round(renderer.info.render.triangles/1000)}k tris · ${Math.round(renderScale*100)}%`;
mapCtx.clearRect(0,0,128,128);mapCtx.fillStyle='#182724';mapCtx.fillRect(0,0,128,128);mapCtx.strokeStyle='#45625b';mapCtx.strokeRect(3,3,122,122);mapCtx.fillStyle='#586762';for(const c of world.colliders)if(c.y2>1)mapCtx.fillRect((c.x1+44)/88*128,(c.z1+44)/88*128,(c.x2-c.x1)/88*128,(c.z2-c.z1)/88*128);for(const b of bots){if(!b.alive)continue;const ally=match.teamMode&&b.team===0,vis=b.pos.distanceTo(player.pos)<40&&visible(player.pos.clone().add(new V(0,1.4,0)),b.pos.clone().add(new V(0,1.2,0)));b.seen=vis;if(!ally&&!vis)continue;mapCtx.fillStyle=ally?'#85bfb6':'#db8768';mapCtx.beginPath();mapCtx.arc((b.pos.x+44)/88*128,(b.pos.z+44)/88*128,2,0,Math.PI*2);mapCtx.fill();}mapCtx.save();mapCtx.translate((player.pos.x+44)/88*128,(player.pos.z+44)/88*128);mapCtx.rotate(-yaw);mapCtx.fillStyle='#ead9ab';mapCtx.beginPath();mapCtx.moveTo(0,-5);mapCtx.lineTo(-3,4);mapCtx.lineTo(3,4);mapCtx.closePath();mapCtx.fill();mapCtx.restore();}
function fixedUpdate(dt){if(appState!=='game')return;updatePlayer(dt);if(appState!=='game')return;updateBots(dt);updateGrenades(dt);if(appState!=='game')return;match.remaining-=dt;if(match.remaining<=0){let won;if(match.mode==='Training Range')won=true;else if(match.mode==='Survival')won=false;else if(match.teamMode)won=match.scores[0]>match.scores[1];else won=player.kills>Math.max(...bots.map(b=>b.kills),0);endMatch(won);}checkWin();}
let footTimer=0;function frame(now){requestAnimationFrame(frame);const raw=(now-lastTime)/1000||STEP;lastTime=now;const dt=Math.min(raw,.07);clock+=dt;frameAvg=lerp(frameAvg,raw*1000,.025);fps=1000/frameAvg;qualityCooldown-=dt;if(save.settings.quality==='Automatic'&&qualityCooldown<=0&&appState==='game'){let next=renderScale;if(fps<36)next=Math.max(.4,renderScale-.08);else if(fps>57)next=Math.min(save.settings.scale,renderScale+.025);if(Math.abs(next-renderScale)>.01){renderScale=next;renderer.setPixelRatio(Math.min(devicePixelRatio,1.5)*renderScale);resize();}qualityCooldown=5;}
accumulator=Math.min(accumulator+dt,STEP*4);while(accumulator>=STEP){fixedUpdate(STEP);accumulator-=STEP;}
environment(dt);for(const p of particlePool)if(p.life>0){p.life-=dt;p.vel.y-=6*dt;p.pos.addScaledVector(p.vel,dt);p.mesh.visible=p.life>0;}for(const t of tracers)if(t.life>0){t.life-=dt;t.mesh.visible=t.life>0;}
if(appState==='game'||appState==='paused'||appState==='results'){const alpha=accumulator/STEP;camera.position.lerpVectors(player.prev,player.pos,alpha);camera.position.y+=player.eye;const speed=Math.hypot(player.vel.x,player.vel.z);camera.rotation.set(pitch,yaw,0);if(save.settings.shake&&shake>0){camera.rotation.z=Math.sin(clock*55)*shake;shake=Math.max(0,shake-dt*.5);}camera.position.x+=Math.cos(yaw)*leanAmount*.42;camera.position.z-=Math.sin(yaw)*leanAmount*.42;camera.rotation.z=-leanAmount*.12;const w=WEAPONS[getWeaponId()],zoom=input.ads?(w.type==='sniper'?6:save.loadout.attachment==='4x scope'?4:1.35):1;scope=lerp(scope,input.ads?1:0,Math.min(1,dt*12));camera.fov=lerp(camera.fov,2*Math.atan(Math.tan(save.settings.fov*Math.PI/360)/zoom)*180/Math.PI,Math.min(1,dt*13));camera.updateProjectionMatrix();const scoped=gun?.userData.scoped&&input.ads;weaponRoot.visible=appState!=='results'&&player.alive&&!scoped;weaponKick=Math.max(0,weaponKick-dt*.55);const sightY=gun?.userData.sightY||.125;weaponRoot.position.set(lerp(.22,0,scope),lerp(-.23,-sightY,scope)-Math.sin(clock*speed*1.3)*.01*(1-scope),-.43+weaponKick*(1-scope*.9));weaponRoot.rotation.set(player.reload>0?Math.sin(player.reload*2)*.25:0,0,player.reload>0?-.45:player.slide>0?.18*(1-scope):0);if(gun?.userData.dot)gun.userData.dot.visible=input.ads&&scope>.9;
if(gun){if(gun.userData.muzzle){gun.userData.flashLife=Math.max(0,gun.userData.flashLife-dt);gun.userData.muzzle.visible=gun.userData.flashLife>0;}const magazine=gun.userData.magazine;if(magazine)magazine.position.y=gun.userData.magazineY-(player.reload>0?Math.sin(player.reload/weaponStats().reload*Math.PI)*.20:0);}$('#scope').hidden=!scoped;$('#scopeLabel').textContent=w.type==='sniper'?'6× / .308':'4× / OPTICAL';$('#crosshair').style.opacity=input.ads?'0':'1';$('#hitmarker').style.opacity=hitTime>0?'1':'0';$('#damageVeil').style.opacity=String(hurtTime>0?.28:player.health<30?.12:0);$('#flash').style.opacity=String(clamp(flash,0,1));hitTime-=dt;hurtTime-=dt;flash=Math.max(0,flash-dt*.65);footTimer-=dt;if(speed>2&&player.grounded&&footTimer<=0&&appState==='game'){AudioManager.play('step');footTimer=.35;}if(appState==='game')hud(dt);}
else{camera.position.set(8+Math.sin(clock*.10)*1.5,3.2,19);camera.lookAt(0,1,9);if(preview)preview.rotation.y=previewYaw+Math.sin(clock*.3)*.08;weaponRoot.visible=false;}
try{const enabled=save.settings.bloom&&!['Ultra Low','Low'].includes(save.settings.quality)&&renderScale>.55&&renderer.capabilities?.isWebGL2&&renderer.extensions?.has('EXT_color_buffer_float');if(bloom)bloom.render(scene,camera,enabled);else renderer.render(scene,camera);}catch(e){fatal(e);} }
const ICONS={play:'M7 4l14 8-14 8z',loadout:'M3 10h13l5 4h-8l-2 6H7l1-6H3zM16 10V6h4',settings:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8M12 2v3m0 14v3M2 12h3m14 0h3M5 5l2 2m10 10 2 2M5 19l2-2M17 7l2-2',training:'M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18M12 7a5 5 0 1 0 0 10 5 5 0 0 0 0-10M12 10v4m-2-2h4',profileBtn:'M8 3h8v11l-4 6-4-6zM8 5H4v5l4 3m8-8h4v5l-4 3',credits:'M5 3h14v18H5zM8 8h8M8 12h8M8 16h5',fullscreenApp:'M3 9V3h6m6 0h6v6M3 15v6h6m6 0h6v-6',installApp:'M12 2v13m-5-5 5 5 5-5M4 16v5h16v-5',fire:'M12 2v5m0 10v5M2 12h5m10 0h5M12 7a5 5 0 1 0 0 10 5 5 0 0 0 0-10',ads:'M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18M12 8v8m-4-4h8',jump:'M12 21V4m-6 7 6-7 6 7',crouch:'M13 3a2 2 0 1 0 0 4 2 2 0 0 0 0-4M12 8l-3 5 7 2-1 6M9 13l-5 6m8-11 6 4 3-3',slide:'M4 18h16M8 5l5 6 6 2M13 11l-4 6-6-3',reload:'M5 7a8 8 0 1 1-1 9M5 2v5h5',swap:'M3 7h17l-4-4M21 17H4l4 4',grenade:'M10 3h4v4m-5 1h6l4 5v6l-4 3H9l-4-3v-6zM14 3h5v5',melee:'M18 2l4 4-12 12-4-4zM4 13l7 7M2 22l5-5',sprint:'M15 2a2 2 0 1 0 0 4 2 2 0 0 0 0-4M7 9l5-2 4 5h5M12 7l-3 7 6 3-1 5M9 14l-5 7',interact:'M4 8h16v13H4zM8 8V4h8v4M8 14h8m-4-4v8',pauseButton:'M8 4v16M16 4v16',leanLeft:'M18 4H9v12m-5-5 5 5 5-5',leanRight:'M6 4h9v12m-5-5 5 5 5-5'};
function iconMarkup(name){return `<svg class="ui-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="${ICONS[name]}" stroke-linecap="round" stroke-linejoin="round"/></svg>`;}
function installIcons(){for(const [id,path] of Object.entries(ICONS)){const el=$('#'+id);if(!el)continue;const text=el.textContent;el.title=text;el.setAttribute?.('aria-label',text);el.innerHTML=iconMarkup(id)+(el.classList.contains?.('control')?'':`<span>${text}</span>`);}$('#fireLeft').innerHTML=iconMarkup('fire');}
installIcons();
$('#play').onclick=lobby;$('#loadout').onclick=loadout;$('#settings').onclick=settings;$('#profileBtn').onclick=profile;$('#training').onclick=()=>{save.config.mode='Training Range';lobby();};$('#credits').onclick=()=>panel('FIELD MANUAL',`<p>FRONTLINE ZERO · Offline playable release 3</p><p>All worlds, characters, firearms and effects are generated by code. Three.js r160 is embedded under its MIT license.</p><p>Keep moving. Jump as you land to retain momentum. In the air, turn while strafing to build speed. Sprint then slide; crouch to lower your stance. Roof stairs use a continuous collision ramp.</p><p>Switch grenade type with TYPE / T. Supply reload is available near the south spawn using SUPPLY / F. Survival has no respawns and ends after five cleared waves. Gun Game advances through eight firearms.</p><p>This is playable release 3, not completion of the full master specification. Eight firearms, simplified procedural arenas and grid-navigation AI are included. Advanced ladders, vaulting, projectile sniper drop, armor customization, the full weapon roster and the complete requested tactical AI are future stages.</p><p>Android device testing is still required. Game-logic tests pass with a simulated DOM and renderer. Browser rendering and Android local-file execution remain unverified. The file never makes network requests.</p>`);$('#back').onclick=()=>{if(appState==='paused'){$('#panel').hidden=true;$('#pause').hidden=false;}else{$('#panel').hidden=true;$('#menu').hidden=false;}};$('#resume').onclick=pause;$('#pauseSettings').onclick=()=>{$('#pause').hidden=true;settings();};$('#endMatch').onclick=()=>{appState='game';endMatch(false);};$('#quit').onclick=goMenu;$('#rematch').onclick=()=>{clearEffects();startMatch();};$('#returnLobby').onclick=()=>{goMenu();lobby();};
buildWorld(MAPS.indexOf(save.config.map),Number(save.config.seed));updateProfile();detectInput();resize();lastTime=performance.now();requestAnimationFrame(frame);
// Read-only state snapshot and explicit simulation actions used for release verification.
window.FZ={get state(){return {appState,player,match,bots,world,input,save,fps,renderScale,renderer};},start:startMatch,fire,reload,switchWeapon,melee,throwGrenade,damageBot,endMatch,goMenu,fixedUpdate,pathTo,blocked,floorAt,buildWorld,visible,look,releasePointer,touchPointers,camera,getEye,updateLean,detectInput,makeGun,setGun,weaponRoot,grenades,smokes,WEAPONS};
})();
