const fs=require('fs'),vm=require('vm'),assert=require('assert');
const elements=new Map();const noop=()=>{};const ctx2=new Proxy({}, {get:(target,key)=>key==='createRadialGradient'?()=>({addColorStop:noop}):noop,set:()=>true});class El{constructor(id){this.id=id;this.hidden=true;this.style={};this.value='';this.children=[];this.dataset={};this.classList={add:noop,remove:noop};this.textContent='';}set innerHTML(v){this.html=v;for(const m of v.matchAll(/<(?:input|select)[^>]*id="([^"]+)"[^>]*>/g)){const el=get(m[1]);const val=m[0].match(/value="([^"]+)"/);if(val)el.value=val[1];const rest=v.slice(m.index),sel=rest.match(/<option value="([^"]+)" selected/);if(sel)el.value=sel[1];}}get innerHTML(){return this.html||'';}get firstChild(){return this.children[0];}get lastChild(){return this.children[this.children.length-1];}appendChild(e){this.children.push(e);}prepend(e){this.children.unshift(e);}remove(){for(const p of elements.values())p.children=p.children.filter(e=>e!==this);}addEventListener(){}getContext(){return ctx2;}getBoundingClientRect(){return {left:100,top:100,width:65,height:65};}setPointerCapture(){}matches(){return false;}click(){this.onclick?.();}}
function get(id){if(!elements.has(id))elements.set(id,new El(id));return elements.get(id);}
for(const m of fs.readFileSync('shell.html','utf8').matchAll(/id="([^"]+)"/g))get(m[1]);const storage={};let raf;const sandbox={console,structuredClone,Math,Float32Array,Uint8Array,Int16Array,ArrayBuffer,performance:{now:()=>0},innerWidth:1000,innerHeight:600,devicePixelRatio:1,navigator:{},localStorage:{getItem:k=>storage[k]||null,setItem:(k,v)=>storage[k]=v},document:{querySelector:s=>elements.get(s.replace('#',''))||null,querySelectorAll:()=>[],createElement:tag=>new El(tag),addEventListener:noop,exitPointerLock:noop},addEventListener:noop,setTimeout:(f,delay)=>{if(delay===70)f();return 1;},clearTimeout:noop,requestAnimationFrame:f=>raf=f,confirm:()=>true,Blob,URL};sandbox.window=sandbox;sandbox.self=sandbox;vm.createContext(sandbox);vm.runInContext(fs.readFileSync('vendor/three.min.js','utf8'),sandbox);vm.runInContext(fs.readFileSync('vendor/Sky.js','utf8'),sandbox);class Renderer{constructor(){this.domElement=new El('canvas');this.shadowMap={};this.info={render:{calls:0,triangles:0}};}setPixelRatio(){}setSize(){}render(){} }sandbox.THREE.WebGLRenderer=Renderer;vm.runInContext(fs.readFileSync('game.js','utf8'),sandbox);const F=sandbox.FZ;assert(F,'initialization failed');const results=[];function test(name,fn){try{fn();results.push({name,passed:true});}catch(e){results.push({name,passed:false,error:e.stack});}}
function start(mode='Training Range',map='Iron Port'){F.goMenu();const s=F.state.save;s.config.mode=mode;s.config.map=map;s.config.duration=180;s.config.limit=20;F.start();assert.equal(F.state.appState,'game');}
test('menu boots and five deterministic maps',()=>{assert.equal(F.state.appState,'menu');for(let theme=0;theme<5;theme++){let w=F.buildWorld(theme,2026),layout=JSON.stringify(w.colliders);F.buildWorld(theme,2026);assert.equal(JSON.stringify(F.state.world.colliders),layout);assert(F.state.world.colliders.length>30);}});
test('navigation connects south and north in all arenas',()=>{for(let theme=0;theme<5;theme++){F.buildWorld(theme,2026);const p=F.pathTo(new sandbox.THREE.Vector3(0,0,36),new sandbox.THREE.Vector3(0,0,-36));assert(p.length>5,'no route theme '+theme);}});
test('all eight firearms fire and reload',()=>{start();for(let id=0;id<8;id++){F.state.save.loadout.primary=id;F.state.player.slot=0;F.state.player.fireCooldown=0;F.state.player.reload=0;F.state.player.ammo[0]=F.WEAPONS[id].mag;const before=F.state.player.ammo[0];F.fire();assert.equal(F.state.player.ammo[0],before-1);F.state.player.ammo[0]=0;F.state.player.fireCooldown=0;F.fire();assert(F.state.player.reload>0);for(let i=0;i<250;i++)F.fixedUpdate(1/60);assert(F.state.player.ammo[0]>0);}});
test('ray hit, headshot and knife hit detection',()=>{start();const s=F.state,p=s.player,b=s.bots[0];s.bots.forEach(e=>e.alive=false);b.alive=true;b.health=100;b.pos.copy(p.pos);b.pos.z-=2;p.fireCooldown=0;F.fire();assert(b.health<100,'bullet misses');assert(p.headshots>0,'headshot not registered');b.alive=true;b.health=100;p.fireCooldown=0;F.melee();assert.equal(b.health,20);});
test('fixed-step movement jump and solid collision',()=>{start();const s=F.state,p=s.player,before=p.pos.clone();s.input.z=-1;for(let i=0;i<30;i++)F.fixedUpdate(1/60);assert(p.pos.distanceTo(before)>1);s.input.jump=true;F.fixedUpdate(1/60);assert(p.vel.y>0);s.input.z=0;for(let i=0;i<120;i++)F.fixedUpdate(1/60);assert(p.pos.y>=F.floorAt(p.pos.x,p.pos.z,p.pos.y)-.01);assert(F.blocked(-20,-24,0));});
test('frag, smoke and flash inventory and physics',()=>{start();for(const type of ['Frag','Smoke','Flash']){F.state.player.throwType=type;const count=F.state.player.grenades;F.throwGrenade();assert.equal(F.state.player.grenades,count-1);for(let i=0;i<170;i++)F.fixedUpdate(1/60);}assert.equal(F.state.player.grenades,0);});
test('weapon switching and attachment magazine',()=>{start();F.switchWeapon();assert.equal(F.state.player.slot,1);F.state.save.loadout.primary=0;F.state.save.loadout.attachment='Extended mag';F.switchWeapon();F.state.player.ammo[0]=0;F.reload();for(let i=0;i<150;i++)F.fixedUpdate(1/60);assert.equal(F.state.player.ammo[0],39);});
test('seven modes start and return results',()=>{for(const mode of ['Team Deathmatch','Free-for-All','Gun Game','Sniper Only','Survival','Training Range','Custom Match']){start(mode);assert(F.state.bots.length>0);F.endMatch(true);assert.equal(F.state.appState,'results');assert(F.state.save.xp>0);}});
test('TDM score limit triggers victory',()=>{start('Team Deathmatch');F.state.match.limit=1;const b=F.state.bots.find(b=>b.team===1);F.damageBot(b,200,false,10,true);assert.equal(F.state.appState,'results');assert.equal(get('resultTitle').textContent,'VICTORY');});
test('survival waves progress and end',()=>{start('Survival');for(let wave=1;wave<=5;wave++){const enemies=[...F.state.bots];for(const b of enemies)if(F.state.appState==='game')F.damageBot(b,200,false,10,true);}assert.equal(F.state.appState,'results');assert.equal(get('resultTitle').textContent,'VICTORY');});
test('Gun Game eight tiers end',()=>{start('Gun Game');for(let i=0;i<8;i++){const b=F.state.bots[0];b.alive=true;b.health=100;F.damageBot(b,200,false,10,true);}assert.equal(F.state.appState,'results');});
test('dual fire buttons release independently',()=>{const s=F.state;F.touchPointers.clear();F.touchPointers.set(1,{action:'fire'});F.touchPointers.set(2,{action:'fire'});s.input.fire=true;F.releasePointer(1);assert(s.input.fire,'right fire must remain held');F.releasePointer(2);assert(!s.input.fire,'last release stops fire');F.touchPointers.set(3,{action:'fire'});F.touchPointers.set(4,{action:'look'});s.input.fire=true;F.releasePointer(3);assert(!s.input.fire,'look pointer must not keep firing');F.touchPointers.clear();});
test('vertical look aligns camera and ballistics',()=>{start();F.state.save.settings.invert=false;F.look(0,-30);raf(16);const d=new sandbox.THREE.Vector3();F.camera.getWorldDirection(d);assert(d.y>0,'upward drag must look up');F.look(0,60);raf(32);F.camera.getWorldDirection(d);assert(d.y<0,'downward drag must look down');});
test('render-loop integration callback',()=>{start();raf(16);raf(32);assert.equal(F.state.appState,'game');});
test('desktop detection and touch switching',()=>{sandbox.matchMedia=()=>({matches:true});assert(F.detectInput());assert(!get('pcHints').hidden);assert(!F.detectInput('touch'));assert(get('pcHints').hidden);F.state.save.settings.inputMode='Keyboard / mouse';assert(F.detectInput('touch'));F.state.save.settings.inputMode='Auto';});
test('peeking shifts shot origin and cannot clip cover',()=>{start();const p=F.state.player;p.pos.set(0,0,32);p.eye=1.65;F.state.input.lean=1;for(let i=0;i<30;i++)F.updateLean(1/60);const eye=new sandbox.THREE.Vector3();F.getEye(eye);assert(eye.x>.4);const obstacle={x1:.20,x2:.8,y1:0,y2:3,z1:31,z2:33};F.state.world.colliders.push(obstacle);F.updateLean(1/60);F.getEye(eye);assert(eye.x<=.101,'head clips wall');F.state.world.colliders.pop();F.state.input.lean=0;});
test('all procedural gun sight centers align with ADS camera ray',()=>{start();for(let id=0;id<8;id++){F.state.save.loadout.primary=id;for(const optic of ['Red dot','Compensator','4x scope']){F.state.save.loadout.attachment=optic;F.setGun();F.state.input.ads=true;for(let i=0;i<100;i++)raf(1000+i*16);const gun=F.weaponRoot.children[0];const sight=new sandbox.THREE.Vector3(0,gun.userData.sightY,-.13);gun.localToWorld(sight);sight.project(F.camera);assert(Math.abs(sight.x)<.003&&Math.abs(sight.y)<.003,'ADS alignment '+id+'/'+optic);if(optic==='4x scope'||id===3)assert(!get('scope').hidden);assert.equal(get('crosshair').style.opacity,'0');}F.state.input.ads=false;}F.state.save.loadout.primary=0;});
console.log(JSON.stringify(results,null,2));fs.writeFileSync('logic-test-results.json',JSON.stringify(results,null,2));if(results.some(r=>!r.passed))process.exitCode=1;
